// Code generated by ent, DO NOT EDIT.

package boardcolumn

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/radius/radius-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldContainsFold(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldProjectID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldTitle, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldStatus, v))
}

// WipLimit applies equality check predicate on the "wip_limit" field. It's identical to WipLimitEQ.
func WipLimit(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldWipLimit, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldContainsFold(FieldProjectID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldContainsFold(FieldTitle, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldContainsFold(FieldStatus, v))
}

// WipLimitEQ applies the EQ predicate on the "wip_limit" field.
func WipLimitEQ(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldWipLimit, v))
}

// WipLimitNEQ applies the NEQ predicate on the "wip_limit" field.
func WipLimitNEQ(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldWipLimit, v))
}

// WipLimitIn applies the In predicate on the "wip_limit" field.
func WipLimitIn(vs ...int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldWipLimit, vs...))
}

// WipLimitNotIn applies the NotIn predicate on the "wip_limit" field.
func WipLimitNotIn(vs ...int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldWipLimit, vs...))
}

// WipLimitGT applies the GT predicate on the "wip_limit" field.
func WipLimitGT(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldWipLimit, v))
}

// WipLimitGTE applies the GTE predicate on the "wip_limit" field.
func WipLimitGTE(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldWipLimit, v))
}

// WipLimitLT applies the LT predicate on the "wip_limit" field.
func WipLimitLT(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldWipLimit, v))
}

// WipLimitLTE applies the LTE predicate on the "wip_limit" field.
func WipLimitLTE(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldWipLimit, v))
}

// WipLimitIsNil applies the IsNil predicate on the "wip_limit" field.
func WipLimitIsNil() predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIsNull(FieldWipLimit))
}

// WipLimitNotNil applies the NotNil predicate on the "wip_limit" field.
func WipLimitNotNil() predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotNull(FieldWipLimit))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BoardColumn {
	return predicate.BoardColumn(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.BoardColumn {
	return predicate.BoardColumn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.BoardColumn {
	return predicate.BoardColumn(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.BoardColumn {
	return predicate.BoardColumn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.Task) predicate.BoardColumn {
	return predicate.BoardColumn(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BoardColumn) predicate.BoardColumn {
	return predicate.BoardColumn(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BoardColumn) predicate.BoardColumn {
	return predicate.BoardColumn(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BoardColumn) predicate.BoardColumn {
	return predicate.BoardColumn(sql.NotPredicates(p))
}
