root = "."
tmp_dir = "tmp"

[build]
  entrypoint       = ["./tmp/main"]
  cmd              = "go build -buildvcs=false -o ./tmp/main ./cmd/api"
  delay            = 1000
  exclude_dir      = ["assets", "tmp", "vendor", "testdata", "build", "migrations"]
  exclude_regex    = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink   = false
  include_ext      = ["go", "yaml", "yml", "toml", "env"]
  kill_delay       = "500ms"
  log              = "build-errors.log"
  send_interrupt   = true
  stop_on_error    = true

[color]
  app     = "cyan"
  build   = "yellow"
  main    = "magenta"
  runner  = "green"
  watcher = "blue"

[log]
  main_only = false
  time      = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll      = true
