// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BoardColumnsColumns holds the columns for the "board_columns" table.
	BoardColumnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "title", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(64)"}},
		{Name: "wip_limit", Type: field.TypeInt, Nullable: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// BoardColumnsTable holds the schema information for the "board_columns" table.
	BoardColumnsTable = &schema.Table{
		Name:       "board_columns",
		Columns:    BoardColumnsColumns,
		PrimaryKey: []*schema.Column{BoardColumnsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "board_columns_projects_board_columns",
				Columns:    []*schema.Column{BoardColumnsColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "boardcolumn_project_id",
				Unique:  false,
				Columns: []*schema.Column{BoardColumnsColumns[7]},
			},
			{
				Name:    "boardcolumn_project_id_status",
				Unique:  true,
				Columns: []*schema.Column{BoardColumnsColumns[7], BoardColumnsColumns[2]},
			},
			{
				Name:    "boardcolumn_project_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{BoardColumnsColumns[7], BoardColumnsColumns[4]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "icon", Type: field.TypeString, Default: "🚀"},
		{Name: "cover", Type: field.TypeEnum, Enums: []string{"emerald", "ocean", "sunset", "violet", "rose", "slate"}, Default: "emerald"},
		{Name: "cover_image_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "on_hold", "completed"}, Default: "active"},
		{Name: "is_favorite", Type: field.TypeBool, Default: false},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "open_tasks", Type: field.TypeInt, Default: 0},
		{Name: "progress", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "workspace_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "projects_workspaces_projects",
				Columns:    []*schema.Column{ProjectsColumns[13]},
				RefColumns: []*schema.Column{WorkspacesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "project_workspace_id",
				Unique:  false,
				Columns: []*schema.Column{ProjectsColumns[13]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"backlog", "todo", "in_progress", "review", "done"}, Default: "todo"},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"low", "medium", "high", "urgent"}, Default: "medium"},
		{Name: "due_at", Type: field.TypeTime, Nullable: true},
		{Name: "label_ids", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "column_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "project_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "assignee_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "workspace_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_board_columns_tasks",
				Columns:    []*schema.Column{TasksColumns[9]},
				RefColumns: []*schema.Column{BoardColumnsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "tasks_projects_tasks",
				Columns:    []*schema.Column{TasksColumns[10]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tasks_users_assigned_tasks",
				Columns:    []*schema.Column{TasksColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "tasks_workspaces_tasks",
				Columns:    []*schema.Column{TasksColumns[12]},
				RefColumns: []*schema.Column{WorkspacesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "task_project_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[10]},
			},
			{
				Name:    "task_workspace_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[12]},
			},
			{
				Name:    "task_column_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[9]},
			},
			{
				Name:    "task_assignee_id",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[11]},
			},
		},
	}
	// TaskActivityLogsColumns holds the columns for the "task_activity_logs" table.
	TaskActivityLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "icon", Type: field.TypeString},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "task_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// TaskActivityLogsTable holds the schema information for the "task_activity_logs" table.
	TaskActivityLogsTable = &schema.Table{
		Name:       "task_activity_logs",
		Columns:    TaskActivityLogsColumns,
		PrimaryKey: []*schema.Column{TaskActivityLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_activity_logs_tasks_activity_logs",
				Columns:    []*schema.Column{TaskActivityLogsColumns[5]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taskactivitylog_task_id",
				Unique:  false,
				Columns: []*schema.Column{TaskActivityLogsColumns[5]},
			},
			{
				Name:    "taskactivitylog_occurred_at",
				Unique:  false,
				Columns: []*schema.Column{TaskActivityLogsColumns[4]},
			},
		},
	}
	// TaskAttachmentsColumns holds the columns for the "task_attachments" table.
	TaskAttachmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "mime_type", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(120)"}},
		{Name: "storage_key", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "url", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "uploaded_at", Type: field.TypeTime},
		{Name: "task_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// TaskAttachmentsTable holds the schema information for the "task_attachments" table.
	TaskAttachmentsTable = &schema.Table{
		Name:       "task_attachments",
		Columns:    TaskAttachmentsColumns,
		PrimaryKey: []*schema.Column{TaskAttachmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_attachments_tasks_attachments",
				Columns:    []*schema.Column{TaskAttachmentsColumns[7]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taskattachment_task_id",
				Unique:  false,
				Columns: []*schema.Column{TaskAttachmentsColumns[7]},
			},
		},
	}
	// TaskChecklistItemsColumns holds the columns for the "task_checklist_items" table.
	TaskChecklistItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "text", Type: field.TypeString},
		{Name: "checked", Type: field.TypeBool, Default: false},
		{Name: "task_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// TaskChecklistItemsTable holds the schema information for the "task_checklist_items" table.
	TaskChecklistItemsTable = &schema.Table{
		Name:       "task_checklist_items",
		Columns:    TaskChecklistItemsColumns,
		PrimaryKey: []*schema.Column{TaskChecklistItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_checklist_items_tasks_checklist_items",
				Columns:    []*schema.Column{TaskChecklistItemsColumns[3]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taskchecklistitem_task_id",
				Unique:  false,
				Columns: []*schema.Column{TaskChecklistItemsColumns[3]},
			},
		},
	}
	// TaskCommentsColumns holds the columns for the "task_comments" table.
	TaskCommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "author_name", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "mention_ids", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "task_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "author_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// TaskCommentsTable holds the schema information for the "task_comments" table.
	TaskCommentsTable = &schema.Table{
		Name:       "task_comments",
		Columns:    TaskCommentsColumns,
		PrimaryKey: []*schema.Column{TaskCommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_comments_tasks_comments",
				Columns:    []*schema.Column{TaskCommentsColumns[6]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "task_comments_users_task_comments",
				Columns:    []*schema.Column{TaskCommentsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "taskcomment_task_id",
				Unique:  false,
				Columns: []*schema.Column{TaskCommentsColumns[6]},
			},
			{
				Name:    "taskcomment_author_id",
				Unique:  false,
				Columns: []*schema.Column{TaskCommentsColumns[7]},
			},
		},
	}
	// TaskSubtasksColumns holds the columns for the "task_subtasks" table.
	TaskSubtasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "title", Type: field.TypeString},
		{Name: "done", Type: field.TypeBool, Default: false},
		{Name: "task_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// TaskSubtasksTable holds the schema information for the "task_subtasks" table.
	TaskSubtasksTable = &schema.Table{
		Name:       "task_subtasks",
		Columns:    TaskSubtasksColumns,
		PrimaryKey: []*schema.Column{TaskSubtasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_subtasks_tasks_subtasks",
				Columns:    []*schema.Column{TaskSubtasksColumns[3]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tasksubtask_task_id",
				Unique:  false,
				Columns: []*schema.Column{TaskSubtasksColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "password_hash", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "email_verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(64)"}},
		{Name: "locale", Type: field.TypeString, Default: "en", SchemaType: map[string]string{"postgres": "varchar(10)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[11]},
			},
		},
	}
	// UserOauthAccountsColumns holds the columns for the "user_oauth_accounts" table.
	UserOauthAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "provider", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(32)"}},
		{Name: "provider_user_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(255)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// UserOauthAccountsTable holds the schema information for the "user_oauth_accounts" table.
	UserOauthAccountsTable = &schema.Table{
		Name:       "user_oauth_accounts",
		Columns:    UserOauthAccountsColumns,
		PrimaryKey: []*schema.Column{UserOauthAccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_oauth_accounts_users_oauth_accounts",
				Columns:    []*schema.Column{UserOauthAccountsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useroauthaccount_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserOauthAccountsColumns[5]},
			},
			{
				Name:    "useroauthaccount_provider_provider_user_id",
				Unique:  true,
				Columns: []*schema.Column{UserOauthAccountsColumns[1], UserOauthAccountsColumns[2]},
			},
		},
	}
	// WorkspacesColumns holds the columns for the "workspaces" table.
	WorkspacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "varchar(255)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WorkspacesTable holds the schema information for the "workspaces" table.
	WorkspacesTable = &schema.Table{
		Name:       "workspaces",
		Columns:    WorkspacesColumns,
		PrimaryKey: []*schema.Column{WorkspacesColumns[0]},
	}
	// WorkspaceMembersColumns holds the columns for the "workspace_members" table.
	WorkspaceMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, SchemaType: map[string]string{"postgres": "citext"}},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "admin", "member", "viewer"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "pending"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "workspace_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// WorkspaceMembersTable holds the schema information for the "workspace_members" table.
	WorkspaceMembersTable = &schema.Table{
		Name:       "workspace_members",
		Columns:    WorkspaceMembersColumns,
		PrimaryKey: []*schema.Column{WorkspaceMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "workspace_members_users_workspace_members",
				Columns:    []*schema.Column{WorkspaceMembersColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "workspace_members_workspaces_members",
				Columns:    []*schema.Column{WorkspaceMembersColumns[8]},
				RefColumns: []*schema.Column{WorkspacesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "workspacemember_workspace_id",
				Unique:  false,
				Columns: []*schema.Column{WorkspaceMembersColumns[8]},
			},
			{
				Name:    "workspacemember_user_id",
				Unique:  false,
				Columns: []*schema.Column{WorkspaceMembersColumns[7]},
			},
			{
				Name:    "workspacemember_workspace_id_email",
				Unique:  true,
				Columns: []*schema.Column{WorkspaceMembersColumns[8], WorkspaceMembersColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BoardColumnsTable,
		ProjectsTable,
		TasksTable,
		TaskActivityLogsTable,
		TaskAttachmentsTable,
		TaskChecklistItemsTable,
		TaskCommentsTable,
		TaskSubtasksTable,
		UsersTable,
		UserOauthAccountsTable,
		WorkspacesTable,
		WorkspaceMembersTable,
	}
)

func init() {
	BoardColumnsTable.ForeignKeys[0].RefTable = ProjectsTable
	BoardColumnsTable.Annotation = &entsql.Annotation{
		Table: "board_columns",
	}
	ProjectsTable.ForeignKeys[0].RefTable = WorkspacesTable
	ProjectsTable.Annotation = &entsql.Annotation{
		Table: "projects",
	}
	ProjectsTable.Annotation.Checks = map[string]string{
		"projects_progress_range": "progress >= 0 AND progress <= 100",
	}
	TasksTable.ForeignKeys[0].RefTable = BoardColumnsTable
	TasksTable.ForeignKeys[1].RefTable = ProjectsTable
	TasksTable.ForeignKeys[2].RefTable = UsersTable
	TasksTable.ForeignKeys[3].RefTable = WorkspacesTable
	TasksTable.Annotation = &entsql.Annotation{
		Table: "tasks",
	}
	TaskActivityLogsTable.ForeignKeys[0].RefTable = TasksTable
	TaskActivityLogsTable.Annotation = &entsql.Annotation{
		Table: "task_activity_logs",
	}
	TaskAttachmentsTable.ForeignKeys[0].RefTable = TasksTable
	TaskAttachmentsTable.Annotation = &entsql.Annotation{
		Table: "task_attachments",
	}
	TaskChecklistItemsTable.ForeignKeys[0].RefTable = TasksTable
	TaskChecklistItemsTable.Annotation = &entsql.Annotation{
		Table: "task_checklist_items",
	}
	TaskCommentsTable.ForeignKeys[0].RefTable = TasksTable
	TaskCommentsTable.ForeignKeys[1].RefTable = UsersTable
	TaskCommentsTable.Annotation = &entsql.Annotation{
		Table: "task_comments",
	}
	TaskSubtasksTable.ForeignKeys[0].RefTable = TasksTable
	TaskSubtasksTable.Annotation = &entsql.Annotation{
		Table: "task_subtasks",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	UsersTable.Annotation.Checks = map[string]string{
		"users_email_format": "email ~* '^[^@]+@[^@]+\\.[^@]+$'",
	}
	UserOauthAccountsTable.ForeignKeys[0].RefTable = UsersTable
	UserOauthAccountsTable.Annotation = &entsql.Annotation{
		Table: "user_oauth_accounts",
	}
	WorkspacesTable.Annotation = &entsql.Annotation{
		Table: "workspaces",
	}
	WorkspaceMembersTable.ForeignKeys[0].RefTable = UsersTable
	WorkspaceMembersTable.ForeignKeys[1].RefTable = WorkspacesTable
	WorkspaceMembersTable.Annotation = &entsql.Annotation{
		Table: "workspace_members",
	}
}
