// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/boardcolumn"
	"github.com/radius/radius-backend/ent/project"
	"github.com/radius/radius-backend/ent/task"
)

// BoardColumnCreate is the builder for creating a BoardColumn entity.
type BoardColumnCreate struct {
	config
	mutation *BoardColumnMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (bcc *BoardColumnCreate) SetProjectID(s string) *BoardColumnCreate {
	bcc.mutation.SetProjectID(s)
	return bcc
}

// SetTitle sets the "title" field.
func (bcc *BoardColumnCreate) SetTitle(s string) *BoardColumnCreate {
	bcc.mutation.SetTitle(s)
	return bcc
}

// SetStatus sets the "status" field.
func (bcc *BoardColumnCreate) SetStatus(s string) *BoardColumnCreate {
	bcc.mutation.SetStatus(s)
	return bcc
}

// SetWipLimit sets the "wip_limit" field.
func (bcc *BoardColumnCreate) SetWipLimit(i int) *BoardColumnCreate {
	bcc.mutation.SetWipLimit(i)
	return bcc
}

// SetNillableWipLimit sets the "wip_limit" field if the given value is not nil.
func (bcc *BoardColumnCreate) SetNillableWipLimit(i *int) *BoardColumnCreate {
	if i != nil {
		bcc.SetWipLimit(*i)
	}
	return bcc
}

// SetSortOrder sets the "sort_order" field.
func (bcc *BoardColumnCreate) SetSortOrder(i int) *BoardColumnCreate {
	bcc.mutation.SetSortOrder(i)
	return bcc
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (bcc *BoardColumnCreate) SetNillableSortOrder(i *int) *BoardColumnCreate {
	if i != nil {
		bcc.SetSortOrder(*i)
	}
	return bcc
}

// SetCreatedAt sets the "created_at" field.
func (bcc *BoardColumnCreate) SetCreatedAt(t time.Time) *BoardColumnCreate {
	bcc.mutation.SetCreatedAt(t)
	return bcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bcc *BoardColumnCreate) SetNillableCreatedAt(t *time.Time) *BoardColumnCreate {
	if t != nil {
		bcc.SetCreatedAt(*t)
	}
	return bcc
}

// SetUpdatedAt sets the "updated_at" field.
func (bcc *BoardColumnCreate) SetUpdatedAt(t time.Time) *BoardColumnCreate {
	bcc.mutation.SetUpdatedAt(t)
	return bcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bcc *BoardColumnCreate) SetNillableUpdatedAt(t *time.Time) *BoardColumnCreate {
	if t != nil {
		bcc.SetUpdatedAt(*t)
	}
	return bcc
}

// SetID sets the "id" field.
func (bcc *BoardColumnCreate) SetID(s string) *BoardColumnCreate {
	bcc.mutation.SetID(s)
	return bcc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bcc *BoardColumnCreate) SetNillableID(s *string) *BoardColumnCreate {
	if s != nil {
		bcc.SetID(*s)
	}
	return bcc
}

// SetProject sets the "project" edge to the Project entity.
func (bcc *BoardColumnCreate) SetProject(p *Project) *BoardColumnCreate {
	return bcc.SetProjectID(p.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (bcc *BoardColumnCreate) AddTaskIDs(ids ...string) *BoardColumnCreate {
	bcc.mutation.AddTaskIDs(ids...)
	return bcc
}

// AddTasks adds the "tasks" edges to the Task entity.
func (bcc *BoardColumnCreate) AddTasks(t ...*Task) *BoardColumnCreate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return bcc.AddTaskIDs(ids...)
}

// Mutation returns the BoardColumnMutation object of the builder.
func (bcc *BoardColumnCreate) Mutation() *BoardColumnMutation {
	return bcc.mutation
}

// Save creates the BoardColumn in the database.
func (bcc *BoardColumnCreate) Save(ctx context.Context) (*BoardColumn, error) {
	bcc.defaults()
	return withHooks(ctx, bcc.sqlSave, bcc.mutation, bcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bcc *BoardColumnCreate) SaveX(ctx context.Context) *BoardColumn {
	v, err := bcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcc *BoardColumnCreate) Exec(ctx context.Context) error {
	_, err := bcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcc *BoardColumnCreate) ExecX(ctx context.Context) {
	if err := bcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bcc *BoardColumnCreate) defaults() {
	if _, ok := bcc.mutation.SortOrder(); !ok {
		v := boardcolumn.DefaultSortOrder
		bcc.mutation.SetSortOrder(v)
	}
	if _, ok := bcc.mutation.CreatedAt(); !ok {
		v := boardcolumn.DefaultCreatedAt()
		bcc.mutation.SetCreatedAt(v)
	}
	if _, ok := bcc.mutation.UpdatedAt(); !ok {
		v := boardcolumn.DefaultUpdatedAt()
		bcc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bcc.mutation.ID(); !ok {
		v := boardcolumn.DefaultID
		bcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bcc *BoardColumnCreate) check() error {
	if _, ok := bcc.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "BoardColumn.project_id"`)}
	}
	if _, ok := bcc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "BoardColumn.title"`)}
	}
	if v, ok := bcc.mutation.Title(); ok {
		if err := boardcolumn.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BoardColumn.title": %w`, err)}
		}
	}
	if _, ok := bcc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BoardColumn.status"`)}
	}
	if v, ok := bcc.mutation.Status(); ok {
		if err := boardcolumn.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BoardColumn.status": %w`, err)}
		}
	}
	if v, ok := bcc.mutation.WipLimit(); ok {
		if err := boardcolumn.WipLimitValidator(v); err != nil {
			return &ValidationError{Name: "wip_limit", err: fmt.Errorf(`ent: validator failed for field "BoardColumn.wip_limit": %w`, err)}
		}
	}
	if _, ok := bcc.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "BoardColumn.sort_order"`)}
	}
	if v, ok := bcc.mutation.SortOrder(); ok {
		if err := boardcolumn.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "BoardColumn.sort_order": %w`, err)}
		}
	}
	if _, ok := bcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BoardColumn.created_at"`)}
	}
	if _, ok := bcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BoardColumn.updated_at"`)}
	}
	if len(bcc.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "BoardColumn.project"`)}
	}
	return nil
}

func (bcc *BoardColumnCreate) sqlSave(ctx context.Context) (*BoardColumn, error) {
	if err := bcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BoardColumn.ID type: %T", _spec.ID.Value)
		}
	}
	bcc.mutation.id = &_node.ID
	bcc.mutation.done = true
	return _node, nil
}

func (bcc *BoardColumnCreate) createSpec() (*BoardColumn, *sqlgraph.CreateSpec) {
	var (
		_node = &BoardColumn{config: bcc.config}
		_spec = sqlgraph.NewCreateSpec(boardcolumn.Table, sqlgraph.NewFieldSpec(boardcolumn.FieldID, field.TypeString))
	)
	if id, ok := bcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bcc.mutation.Title(); ok {
		_spec.SetField(boardcolumn.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := bcc.mutation.Status(); ok {
		_spec.SetField(boardcolumn.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := bcc.mutation.WipLimit(); ok {
		_spec.SetField(boardcolumn.FieldWipLimit, field.TypeInt, value)
		_node.WipLimit = &value
	}
	if value, ok := bcc.mutation.SortOrder(); ok {
		_spec.SetField(boardcolumn.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := bcc.mutation.CreatedAt(); ok {
		_spec.SetField(boardcolumn.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bcc.mutation.UpdatedAt(); ok {
		_spec.SetField(boardcolumn.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := bcc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   boardcolumn.ProjectTable,
			Columns: []string{boardcolumn.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bcc.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   boardcolumn.TasksTable,
			Columns: []string{boardcolumn.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BoardColumnCreateBulk is the builder for creating many BoardColumn entities in bulk.
type BoardColumnCreateBulk struct {
	config
	err      error
	builders []*BoardColumnCreate
}

// Save creates the BoardColumn entities in the database.
func (bccb *BoardColumnCreateBulk) Save(ctx context.Context) ([]*BoardColumn, error) {
	if bccb.err != nil {
		return nil, bccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bccb.builders))
	nodes := make([]*BoardColumn, len(bccb.builders))
	mutators := make([]Mutator, len(bccb.builders))
	for i := range bccb.builders {
		func(i int, root context.Context) {
			builder := bccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BoardColumnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bccb *BoardColumnCreateBulk) SaveX(ctx context.Context) []*BoardColumn {
	v, err := bccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bccb *BoardColumnCreateBulk) Exec(ctx context.Context) error {
	_, err := bccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bccb *BoardColumnCreateBulk) ExecX(ctx context.Context) {
	if err := bccb.Exec(ctx); err != nil {
		panic(err)
	}
}
