// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/radius/radius-backend/ent/boardcolumn"
	"github.com/radius/radius-backend/ent/project"
	"github.com/radius/radius-backend/ent/schema"
	"github.com/radius/radius-backend/ent/user"
	"github.com/radius/radius-backend/ent/useroauthaccount"
	"github.com/radius/radius-backend/ent/workspace"
	"github.com/radius/radius-backend/ent/workspacemember"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	boardcolumnFields := schema.BoardColumn{}.Fields()
	_ = boardcolumnFields
	// boardcolumnDescTitle is the schema descriptor for title field.
	boardcolumnDescTitle := boardcolumnFields[2].Descriptor()
	// boardcolumn.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	boardcolumn.TitleValidator = boardcolumnDescTitle.Validators[0].(func(string) error)
	// boardcolumnDescStatus is the schema descriptor for status field.
	boardcolumnDescStatus := boardcolumnFields[3].Descriptor()
	// boardcolumn.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	boardcolumn.StatusValidator = boardcolumnDescStatus.Validators[0].(func(string) error)
	// boardcolumnDescWipLimit is the schema descriptor for wip_limit field.
	boardcolumnDescWipLimit := boardcolumnFields[4].Descriptor()
	// boardcolumn.WipLimitValidator is a validator for the "wip_limit" field. It is called by the builders before save.
	boardcolumn.WipLimitValidator = boardcolumnDescWipLimit.Validators[0].(func(int) error)
	// boardcolumnDescSortOrder is the schema descriptor for sort_order field.
	boardcolumnDescSortOrder := boardcolumnFields[5].Descriptor()
	// boardcolumn.DefaultSortOrder holds the default value on creation for the sort_order field.
	boardcolumn.DefaultSortOrder = boardcolumnDescSortOrder.Default.(int)
	// boardcolumn.SortOrderValidator is a validator for the "sort_order" field. It is called by the builders before save.
	boardcolumn.SortOrderValidator = boardcolumnDescSortOrder.Validators[0].(func(int) error)
	// boardcolumnDescCreatedAt is the schema descriptor for created_at field.
	boardcolumnDescCreatedAt := boardcolumnFields[6].Descriptor()
	// boardcolumn.DefaultCreatedAt holds the default value on creation for the created_at field.
	boardcolumn.DefaultCreatedAt = boardcolumnDescCreatedAt.Default.(func() time.Time)
	// boardcolumnDescUpdatedAt is the schema descriptor for updated_at field.
	boardcolumnDescUpdatedAt := boardcolumnFields[7].Descriptor()
	// boardcolumn.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	boardcolumn.DefaultUpdatedAt = boardcolumnDescUpdatedAt.Default.(func() time.Time)
	// boardcolumn.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	boardcolumn.UpdateDefaultUpdatedAt = boardcolumnDescUpdatedAt.UpdateDefault.(func() time.Time)
	// boardcolumnDescID is the schema descriptor for id field.
	boardcolumnDescID := boardcolumnFields[0].Descriptor()
	// boardcolumn.DefaultID holds the default value on creation for the id field.
	boardcolumn.DefaultID = boardcolumnDescID.Default.(string)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[2].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescIcon is the schema descriptor for icon field.
	projectDescIcon := projectFields[4].Descriptor()
	// project.DefaultIcon holds the default value on creation for the icon field.
	project.DefaultIcon = projectDescIcon.Default.(string)
	// project.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	project.IconValidator = projectDescIcon.Validators[0].(func(string) error)
	// projectDescIsFavorite is the schema descriptor for is_favorite field.
	projectDescIsFavorite := projectFields[8].Descriptor()
	// project.DefaultIsFavorite holds the default value on creation for the is_favorite field.
	project.DefaultIsFavorite = projectDescIsFavorite.Default.(bool)
	// projectDescOpenTasks is the schema descriptor for open_tasks field.
	projectDescOpenTasks := projectFields[10].Descriptor()
	// project.DefaultOpenTasks holds the default value on creation for the open_tasks field.
	project.DefaultOpenTasks = projectDescOpenTasks.Default.(int)
	// project.OpenTasksValidator is a validator for the "open_tasks" field. It is called by the builders before save.
	project.OpenTasksValidator = projectDescOpenTasks.Validators[0].(func(int) error)
	// projectDescProgress is the schema descriptor for progress field.
	projectDescProgress := projectFields[11].Descriptor()
	// project.DefaultProgress holds the default value on creation for the progress field.
	project.DefaultProgress = projectDescProgress.Default.(int)
	// project.ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	project.ProgressValidator = func() func(int) error {
		validators := projectDescProgress.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(progress int) error {
			for _, fn := range fns {
				if err := fn(progress); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[12].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[13].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescLocale is the schema descriptor for locale field.
	userDescLocale := userFields[8].Descriptor()
	// user.DefaultLocale holds the default value on creation for the locale field.
	user.DefaultLocale = userDescLocale.Default.(string)
	// user.LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	user.LocaleValidator = userDescLocale.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(string)
	useroauthaccountFields := schema.UserOAuthAccount{}.Fields()
	_ = useroauthaccountFields
	// useroauthaccountDescProvider is the schema descriptor for provider field.
	useroauthaccountDescProvider := useroauthaccountFields[2].Descriptor()
	// useroauthaccount.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	useroauthaccount.ProviderValidator = useroauthaccountDescProvider.Validators[0].(func(string) error)
	// useroauthaccountDescProviderUserID is the schema descriptor for provider_user_id field.
	useroauthaccountDescProviderUserID := useroauthaccountFields[3].Descriptor()
	// useroauthaccount.ProviderUserIDValidator is a validator for the "provider_user_id" field. It is called by the builders before save.
	useroauthaccount.ProviderUserIDValidator = useroauthaccountDescProviderUserID.Validators[0].(func(string) error)
	// useroauthaccountDescCreatedAt is the schema descriptor for created_at field.
	useroauthaccountDescCreatedAt := useroauthaccountFields[4].Descriptor()
	// useroauthaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	useroauthaccount.DefaultCreatedAt = useroauthaccountDescCreatedAt.Default.(func() time.Time)
	// useroauthaccountDescUpdatedAt is the schema descriptor for updated_at field.
	useroauthaccountDescUpdatedAt := useroauthaccountFields[5].Descriptor()
	// useroauthaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useroauthaccount.DefaultUpdatedAt = useroauthaccountDescUpdatedAt.Default.(func() time.Time)
	// useroauthaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useroauthaccount.UpdateDefaultUpdatedAt = useroauthaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// useroauthaccountDescID is the schema descriptor for id field.
	useroauthaccountDescID := useroauthaccountFields[0].Descriptor()
	// useroauthaccount.DefaultID holds the default value on creation for the id field.
	useroauthaccount.DefaultID = useroauthaccountDescID.Default.(string)
	workspaceFields := schema.Workspace{}.Fields()
	_ = workspaceFields
	// workspaceDescName is the schema descriptor for name field.
	workspaceDescName := workspaceFields[1].Descriptor()
	// workspace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workspace.NameValidator = workspaceDescName.Validators[0].(func(string) error)
	// workspaceDescSlug is the schema descriptor for slug field.
	workspaceDescSlug := workspaceFields[2].Descriptor()
	// workspace.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	workspace.SlugValidator = workspaceDescSlug.Validators[0].(func(string) error)
	// workspaceDescCreatedAt is the schema descriptor for created_at field.
	workspaceDescCreatedAt := workspaceFields[3].Descriptor()
	// workspace.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspace.DefaultCreatedAt = workspaceDescCreatedAt.Default.(func() time.Time)
	// workspaceDescUpdatedAt is the schema descriptor for updated_at field.
	workspaceDescUpdatedAt := workspaceFields[4].Descriptor()
	// workspace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspace.DefaultUpdatedAt = workspaceDescUpdatedAt.Default.(func() time.Time)
	// workspace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspace.UpdateDefaultUpdatedAt = workspaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspaceDescID is the schema descriptor for id field.
	workspaceDescID := workspaceFields[0].Descriptor()
	// workspace.DefaultID holds the default value on creation for the id field.
	workspace.DefaultID = workspaceDescID.Default.(string)
	workspacememberFields := schema.WorkspaceMember{}.Fields()
	_ = workspacememberFields
	// workspacememberDescName is the schema descriptor for name field.
	workspacememberDescName := workspacememberFields[3].Descriptor()
	// workspacemember.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workspacemember.NameValidator = workspacememberDescName.Validators[0].(func(string) error)
	// workspacememberDescEmail is the schema descriptor for email field.
	workspacememberDescEmail := workspacememberFields[4].Descriptor()
	// workspacemember.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	workspacemember.EmailValidator = workspacememberDescEmail.Validators[0].(func(string) error)
	// workspacememberDescCreatedAt is the schema descriptor for created_at field.
	workspacememberDescCreatedAt := workspacememberFields[7].Descriptor()
	// workspacemember.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspacemember.DefaultCreatedAt = workspacememberDescCreatedAt.Default.(func() time.Time)
	// workspacememberDescUpdatedAt is the schema descriptor for updated_at field.
	workspacememberDescUpdatedAt := workspacememberFields[8].Descriptor()
	// workspacemember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspacemember.DefaultUpdatedAt = workspacememberDescUpdatedAt.Default.(func() time.Time)
	// workspacemember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspacemember.UpdateDefaultUpdatedAt = workspacememberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspacememberDescID is the schema descriptor for id field.
	workspacememberDescID := workspacememberFields[0].Descriptor()
	// workspacemember.DefaultID holds the default value on creation for the id field.
	workspacemember.DefaultID = workspacememberDescID.Default.(string)
}
