// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/radius/radius-backend/ent/schema"
	"github.com/radius/radius-backend/ent/user"
	"github.com/radius/radius-backend/ent/useroauthaccount"
	"github.com/radius/radius-backend/ent/workspace"
	"github.com/radius/radius-backend/ent/workspacemember"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescLocale is the schema descriptor for locale field.
	userDescLocale := userFields[8].Descriptor()
	// user.DefaultLocale holds the default value on creation for the locale field.
	user.DefaultLocale = userDescLocale.Default.(string)
	// user.LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	user.LocaleValidator = userDescLocale.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(string)
	useroauthaccountFields := schema.UserOAuthAccount{}.Fields()
	_ = useroauthaccountFields
	// useroauthaccountDescProvider is the schema descriptor for provider field.
	useroauthaccountDescProvider := useroauthaccountFields[2].Descriptor()
	// useroauthaccount.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	useroauthaccount.ProviderValidator = useroauthaccountDescProvider.Validators[0].(func(string) error)
	// useroauthaccountDescProviderUserID is the schema descriptor for provider_user_id field.
	useroauthaccountDescProviderUserID := useroauthaccountFields[3].Descriptor()
	// useroauthaccount.ProviderUserIDValidator is a validator for the "provider_user_id" field. It is called by the builders before save.
	useroauthaccount.ProviderUserIDValidator = useroauthaccountDescProviderUserID.Validators[0].(func(string) error)
	// useroauthaccountDescCreatedAt is the schema descriptor for created_at field.
	useroauthaccountDescCreatedAt := useroauthaccountFields[4].Descriptor()
	// useroauthaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	useroauthaccount.DefaultCreatedAt = useroauthaccountDescCreatedAt.Default.(func() time.Time)
	// useroauthaccountDescUpdatedAt is the schema descriptor for updated_at field.
	useroauthaccountDescUpdatedAt := useroauthaccountFields[5].Descriptor()
	// useroauthaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useroauthaccount.DefaultUpdatedAt = useroauthaccountDescUpdatedAt.Default.(func() time.Time)
	// useroauthaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useroauthaccount.UpdateDefaultUpdatedAt = useroauthaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// useroauthaccountDescID is the schema descriptor for id field.
	useroauthaccountDescID := useroauthaccountFields[0].Descriptor()
	// useroauthaccount.DefaultID holds the default value on creation for the id field.
	useroauthaccount.DefaultID = useroauthaccountDescID.Default.(string)
	workspaceFields := schema.Workspace{}.Fields()
	_ = workspaceFields
	// workspaceDescName is the schema descriptor for name field.
	workspaceDescName := workspaceFields[1].Descriptor()
	// workspace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workspace.NameValidator = workspaceDescName.Validators[0].(func(string) error)
	// workspaceDescSlug is the schema descriptor for slug field.
	workspaceDescSlug := workspaceFields[2].Descriptor()
	// workspace.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	workspace.SlugValidator = workspaceDescSlug.Validators[0].(func(string) error)
	// workspaceDescCreatedAt is the schema descriptor for created_at field.
	workspaceDescCreatedAt := workspaceFields[3].Descriptor()
	// workspace.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspace.DefaultCreatedAt = workspaceDescCreatedAt.Default.(func() time.Time)
	// workspaceDescUpdatedAt is the schema descriptor for updated_at field.
	workspaceDescUpdatedAt := workspaceFields[4].Descriptor()
	// workspace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspace.DefaultUpdatedAt = workspaceDescUpdatedAt.Default.(func() time.Time)
	// workspace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspace.UpdateDefaultUpdatedAt = workspaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspaceDescID is the schema descriptor for id field.
	workspaceDescID := workspaceFields[0].Descriptor()
	// workspace.DefaultID holds the default value on creation for the id field.
	workspace.DefaultID = workspaceDescID.Default.(string)
	workspacememberFields := schema.WorkspaceMember{}.Fields()
	_ = workspacememberFields
	// workspacememberDescName is the schema descriptor for name field.
	workspacememberDescName := workspacememberFields[3].Descriptor()
	// workspacemember.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workspacemember.NameValidator = workspacememberDescName.Validators[0].(func(string) error)
	// workspacememberDescEmail is the schema descriptor for email field.
	workspacememberDescEmail := workspacememberFields[4].Descriptor()
	// workspacemember.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	workspacemember.EmailValidator = workspacememberDescEmail.Validators[0].(func(string) error)
	// workspacememberDescCreatedAt is the schema descriptor for created_at field.
	workspacememberDescCreatedAt := workspacememberFields[7].Descriptor()
	// workspacemember.DefaultCreatedAt holds the default value on creation for the created_at field.
	workspacemember.DefaultCreatedAt = workspacememberDescCreatedAt.Default.(func() time.Time)
	// workspacememberDescUpdatedAt is the schema descriptor for updated_at field.
	workspacememberDescUpdatedAt := workspacememberFields[8].Descriptor()
	// workspacemember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workspacemember.DefaultUpdatedAt = workspacememberDescUpdatedAt.Default.(func() time.Time)
	// workspacemember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workspacemember.UpdateDefaultUpdatedAt = workspacememberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workspacememberDescID is the schema descriptor for id field.
	workspacememberDescID := workspacememberFields[0].Descriptor()
	// workspacemember.DefaultID holds the default value on creation for the id field.
	workspacemember.DefaultID = workspacememberDescID.Default.(string)
}
