// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/task"
	"github.com/radius/radius-backend/ent/taskchecklistitem"
)

// TaskChecklistItemQuery is the builder for querying TaskChecklistItem entities.
type TaskChecklistItemQuery struct {
	config
	ctx        *QueryContext
	order      []taskchecklistitem.OrderOption
	inters     []Interceptor
	predicates []predicate.TaskChecklistItem
	withTask   *TaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskChecklistItemQuery builder.
func (tciq *TaskChecklistItemQuery) Where(ps ...predicate.TaskChecklistItem) *TaskChecklistItemQuery {
	tciq.predicates = append(tciq.predicates, ps...)
	return tciq
}

// Limit the number of records to be returned by this query.
func (tciq *TaskChecklistItemQuery) Limit(limit int) *TaskChecklistItemQuery {
	tciq.ctx.Limit = &limit
	return tciq
}

// Offset to start from.
func (tciq *TaskChecklistItemQuery) Offset(offset int) *TaskChecklistItemQuery {
	tciq.ctx.Offset = &offset
	return tciq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tciq *TaskChecklistItemQuery) Unique(unique bool) *TaskChecklistItemQuery {
	tciq.ctx.Unique = &unique
	return tciq
}

// Order specifies how the records should be ordered.
func (tciq *TaskChecklistItemQuery) Order(o ...taskchecklistitem.OrderOption) *TaskChecklistItemQuery {
	tciq.order = append(tciq.order, o...)
	return tciq
}

// QueryTask chains the current query on the "task" edge.
func (tciq *TaskChecklistItemQuery) QueryTask() *TaskQuery {
	query := (&TaskClient{config: tciq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tciq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tciq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taskchecklistitem.Table, taskchecklistitem.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskchecklistitem.TaskTable, taskchecklistitem.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(tciq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TaskChecklistItem entity from the query.
// Returns a *NotFoundError when no TaskChecklistItem was found.
func (tciq *TaskChecklistItemQuery) First(ctx context.Context) (*TaskChecklistItem, error) {
	nodes, err := tciq.Limit(1).All(setContextOp(ctx, tciq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taskchecklistitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) FirstX(ctx context.Context) *TaskChecklistItem {
	node, err := tciq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskChecklistItem ID from the query.
// Returns a *NotFoundError when no TaskChecklistItem ID was found.
func (tciq *TaskChecklistItemQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tciq.Limit(1).IDs(setContextOp(ctx, tciq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taskchecklistitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) FirstIDX(ctx context.Context) string {
	id, err := tciq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskChecklistItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskChecklistItem entity is found.
// Returns a *NotFoundError when no TaskChecklistItem entities are found.
func (tciq *TaskChecklistItemQuery) Only(ctx context.Context) (*TaskChecklistItem, error) {
	nodes, err := tciq.Limit(2).All(setContextOp(ctx, tciq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taskchecklistitem.Label}
	default:
		return nil, &NotSingularError{taskchecklistitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) OnlyX(ctx context.Context) *TaskChecklistItem {
	node, err := tciq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskChecklistItem ID in the query.
// Returns a *NotSingularError when more than one TaskChecklistItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (tciq *TaskChecklistItemQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tciq.Limit(2).IDs(setContextOp(ctx, tciq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taskchecklistitem.Label}
	default:
		err = &NotSingularError{taskchecklistitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) OnlyIDX(ctx context.Context) string {
	id, err := tciq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskChecklistItems.
func (tciq *TaskChecklistItemQuery) All(ctx context.Context) ([]*TaskChecklistItem, error) {
	ctx = setContextOp(ctx, tciq.ctx, ent.OpQueryAll)
	if err := tciq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TaskChecklistItem, *TaskChecklistItemQuery]()
	return withInterceptors[[]*TaskChecklistItem](ctx, tciq, qr, tciq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) AllX(ctx context.Context) []*TaskChecklistItem {
	nodes, err := tciq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskChecklistItem IDs.
func (tciq *TaskChecklistItemQuery) IDs(ctx context.Context) (ids []string, err error) {
	if tciq.ctx.Unique == nil && tciq.path != nil {
		tciq.Unique(true)
	}
	ctx = setContextOp(ctx, tciq.ctx, ent.OpQueryIDs)
	if err = tciq.Select(taskchecklistitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) IDsX(ctx context.Context) []string {
	ids, err := tciq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tciq *TaskChecklistItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tciq.ctx, ent.OpQueryCount)
	if err := tciq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tciq, querierCount[*TaskChecklistItemQuery](), tciq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) CountX(ctx context.Context) int {
	count, err := tciq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tciq *TaskChecklistItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tciq.ctx, ent.OpQueryExist)
	switch _, err := tciq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tciq *TaskChecklistItemQuery) ExistX(ctx context.Context) bool {
	exist, err := tciq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskChecklistItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tciq *TaskChecklistItemQuery) Clone() *TaskChecklistItemQuery {
	if tciq == nil {
		return nil
	}
	return &TaskChecklistItemQuery{
		config:     tciq.config,
		ctx:        tciq.ctx.Clone(),
		order:      append([]taskchecklistitem.OrderOption{}, tciq.order...),
		inters:     append([]Interceptor{}, tciq.inters...),
		predicates: append([]predicate.TaskChecklistItem{}, tciq.predicates...),
		withTask:   tciq.withTask.Clone(),
		// clone intermediate query.
		sql:  tciq.sql.Clone(),
		path: tciq.path,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (tciq *TaskChecklistItemQuery) WithTask(opts ...func(*TaskQuery)) *TaskChecklistItemQuery {
	query := (&TaskClient{config: tciq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tciq.withTask = query
	return tciq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskChecklistItem.Query().
//		GroupBy(taskchecklistitem.FieldTaskID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tciq *TaskChecklistItemQuery) GroupBy(field string, fields ...string) *TaskChecklistItemGroupBy {
	tciq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TaskChecklistItemGroupBy{build: tciq}
	grbuild.flds = &tciq.ctx.Fields
	grbuild.label = taskchecklistitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//	}
//
//	client.TaskChecklistItem.Query().
//		Select(taskchecklistitem.FieldTaskID).
//		Scan(ctx, &v)
func (tciq *TaskChecklistItemQuery) Select(fields ...string) *TaskChecklistItemSelect {
	tciq.ctx.Fields = append(tciq.ctx.Fields, fields...)
	sbuild := &TaskChecklistItemSelect{TaskChecklistItemQuery: tciq}
	sbuild.label = taskchecklistitem.Label
	sbuild.flds, sbuild.scan = &tciq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TaskChecklistItemSelect configured with the given aggregations.
func (tciq *TaskChecklistItemQuery) Aggregate(fns ...AggregateFunc) *TaskChecklistItemSelect {
	return tciq.Select().Aggregate(fns...)
}

func (tciq *TaskChecklistItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tciq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tciq); err != nil {
				return err
			}
		}
	}
	for _, f := range tciq.ctx.Fields {
		if !taskchecklistitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tciq.path != nil {
		prev, err := tciq.path(ctx)
		if err != nil {
			return err
		}
		tciq.sql = prev
	}
	return nil
}

func (tciq *TaskChecklistItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaskChecklistItem, error) {
	var (
		nodes       = []*TaskChecklistItem{}
		_spec       = tciq.querySpec()
		loadedTypes = [1]bool{
			tciq.withTask != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaskChecklistItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaskChecklistItem{config: tciq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tciq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tciq.withTask; query != nil {
		if err := tciq.loadTask(ctx, query, nodes, nil,
			func(n *TaskChecklistItem, e *Task) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tciq *TaskChecklistItemQuery) loadTask(ctx context.Context, query *TaskQuery, nodes []*TaskChecklistItem, init func(*TaskChecklistItem), assign func(*TaskChecklistItem, *Task)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TaskChecklistItem)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tciq *TaskChecklistItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tciq.querySpec()
	_spec.Node.Columns = tciq.ctx.Fields
	if len(tciq.ctx.Fields) > 0 {
		_spec.Unique = tciq.ctx.Unique != nil && *tciq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tciq.driver, _spec)
}

func (tciq *TaskChecklistItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(taskchecklistitem.Table, taskchecklistitem.Columns, sqlgraph.NewFieldSpec(taskchecklistitem.FieldID, field.TypeString))
	_spec.From = tciq.sql
	if unique := tciq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tciq.path != nil {
		_spec.Unique = true
	}
	if fields := tciq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskchecklistitem.FieldID)
		for i := range fields {
			if fields[i] != taskchecklistitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tciq.withTask != nil {
			_spec.Node.AddColumnOnce(taskchecklistitem.FieldTaskID)
		}
	}
	if ps := tciq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tciq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tciq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tciq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tciq *TaskChecklistItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tciq.driver.Dialect())
	t1 := builder.Table(taskchecklistitem.Table)
	columns := tciq.ctx.Fields
	if len(columns) == 0 {
		columns = taskchecklistitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tciq.sql != nil {
		selector = tciq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tciq.ctx.Unique != nil && *tciq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tciq.predicates {
		p(selector)
	}
	for _, p := range tciq.order {
		p(selector)
	}
	if offset := tciq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tciq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaskChecklistItemGroupBy is the group-by builder for TaskChecklistItem entities.
type TaskChecklistItemGroupBy struct {
	selector
	build *TaskChecklistItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tcigb *TaskChecklistItemGroupBy) Aggregate(fns ...AggregateFunc) *TaskChecklistItemGroupBy {
	tcigb.fns = append(tcigb.fns, fns...)
	return tcigb
}

// Scan applies the selector query and scans the result into the given value.
func (tcigb *TaskChecklistItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcigb.build.ctx, ent.OpQueryGroupBy)
	if err := tcigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskChecklistItemQuery, *TaskChecklistItemGroupBy](ctx, tcigb.build, tcigb, tcigb.build.inters, v)
}

func (tcigb *TaskChecklistItemGroupBy) sqlScan(ctx context.Context, root *TaskChecklistItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tcigb.fns))
	for _, fn := range tcigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tcigb.flds)+len(tcigb.fns))
		for _, f := range *tcigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tcigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TaskChecklistItemSelect is the builder for selecting fields of TaskChecklistItem entities.
type TaskChecklistItemSelect struct {
	*TaskChecklistItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tcis *TaskChecklistItemSelect) Aggregate(fns ...AggregateFunc) *TaskChecklistItemSelect {
	tcis.fns = append(tcis.fns, fns...)
	return tcis
}

// Scan applies the selector query and scans the result into the given value.
func (tcis *TaskChecklistItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcis.ctx, ent.OpQuerySelect)
	if err := tcis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskChecklistItemQuery, *TaskChecklistItemSelect](ctx, tcis.TaskChecklistItemQuery, tcis, tcis.inters, v)
}

func (tcis *TaskChecklistItemSelect) sqlScan(ctx context.Context, root *TaskChecklistItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tcis.fns))
	for _, fn := range tcis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tcis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
