// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/task"
	"github.com/radius/radius-backend/ent/taskattachment"
)

// TaskAttachmentQuery is the builder for querying TaskAttachment entities.
type TaskAttachmentQuery struct {
	config
	ctx        *QueryContext
	order      []taskattachment.OrderOption
	inters     []Interceptor
	predicates []predicate.TaskAttachment
	withTask   *TaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskAttachmentQuery builder.
func (taq *TaskAttachmentQuery) Where(ps ...predicate.TaskAttachment) *TaskAttachmentQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit the number of records to be returned by this query.
func (taq *TaskAttachmentQuery) Limit(limit int) *TaskAttachmentQuery {
	taq.ctx.Limit = &limit
	return taq
}

// Offset to start from.
func (taq *TaskAttachmentQuery) Offset(offset int) *TaskAttachmentQuery {
	taq.ctx.Offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *TaskAttachmentQuery) Unique(unique bool) *TaskAttachmentQuery {
	taq.ctx.Unique = &unique
	return taq
}

// Order specifies how the records should be ordered.
func (taq *TaskAttachmentQuery) Order(o ...taskattachment.OrderOption) *TaskAttachmentQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// QueryTask chains the current query on the "task" edge.
func (taq *TaskAttachmentQuery) QueryTask() *TaskQuery {
	query := (&TaskClient{config: taq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := taq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taskattachment.Table, taskattachment.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskattachment.TaskTable, taskattachment.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(taq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TaskAttachment entity from the query.
// Returns a *NotFoundError when no TaskAttachment was found.
func (taq *TaskAttachmentQuery) First(ctx context.Context) (*TaskAttachment, error) {
	nodes, err := taq.Limit(1).All(setContextOp(ctx, taq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taskattachment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *TaskAttachmentQuery) FirstX(ctx context.Context) *TaskAttachment {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskAttachment ID from the query.
// Returns a *NotFoundError when no TaskAttachment ID was found.
func (taq *TaskAttachmentQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = taq.Limit(1).IDs(setContextOp(ctx, taq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taskattachment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *TaskAttachmentQuery) FirstIDX(ctx context.Context) string {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskAttachment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskAttachment entity is found.
// Returns a *NotFoundError when no TaskAttachment entities are found.
func (taq *TaskAttachmentQuery) Only(ctx context.Context) (*TaskAttachment, error) {
	nodes, err := taq.Limit(2).All(setContextOp(ctx, taq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taskattachment.Label}
	default:
		return nil, &NotSingularError{taskattachment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *TaskAttachmentQuery) OnlyX(ctx context.Context) *TaskAttachment {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskAttachment ID in the query.
// Returns a *NotSingularError when more than one TaskAttachment ID is found.
// Returns a *NotFoundError when no entities are found.
func (taq *TaskAttachmentQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = taq.Limit(2).IDs(setContextOp(ctx, taq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taskattachment.Label}
	default:
		err = &NotSingularError{taskattachment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *TaskAttachmentQuery) OnlyIDX(ctx context.Context) string {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskAttachments.
func (taq *TaskAttachmentQuery) All(ctx context.Context) ([]*TaskAttachment, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryAll)
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TaskAttachment, *TaskAttachmentQuery]()
	return withInterceptors[[]*TaskAttachment](ctx, taq, qr, taq.inters)
}

// AllX is like All, but panics if an error occurs.
func (taq *TaskAttachmentQuery) AllX(ctx context.Context) []*TaskAttachment {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskAttachment IDs.
func (taq *TaskAttachmentQuery) IDs(ctx context.Context) (ids []string, err error) {
	if taq.ctx.Unique == nil && taq.path != nil {
		taq.Unique(true)
	}
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryIDs)
	if err = taq.Select(taskattachment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *TaskAttachmentQuery) IDsX(ctx context.Context) []string {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *TaskAttachmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryCount)
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, taq, querierCount[*TaskAttachmentQuery](), taq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (taq *TaskAttachmentQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *TaskAttachmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryExist)
	switch _, err := taq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *TaskAttachmentQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskAttachmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *TaskAttachmentQuery) Clone() *TaskAttachmentQuery {
	if taq == nil {
		return nil
	}
	return &TaskAttachmentQuery{
		config:     taq.config,
		ctx:        taq.ctx.Clone(),
		order:      append([]taskattachment.OrderOption{}, taq.order...),
		inters:     append([]Interceptor{}, taq.inters...),
		predicates: append([]predicate.TaskAttachment{}, taq.predicates...),
		withTask:   taq.withTask.Clone(),
		// clone intermediate query.
		sql:  taq.sql.Clone(),
		path: taq.path,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (taq *TaskAttachmentQuery) WithTask(opts ...func(*TaskQuery)) *TaskAttachmentQuery {
	query := (&TaskClient{config: taq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	taq.withTask = query
	return taq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskAttachment.Query().
//		GroupBy(taskattachment.FieldTaskID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (taq *TaskAttachmentQuery) GroupBy(field string, fields ...string) *TaskAttachmentGroupBy {
	taq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TaskAttachmentGroupBy{build: taq}
	grbuild.flds = &taq.ctx.Fields
	grbuild.label = taskattachment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//	}
//
//	client.TaskAttachment.Query().
//		Select(taskattachment.FieldTaskID).
//		Scan(ctx, &v)
func (taq *TaskAttachmentQuery) Select(fields ...string) *TaskAttachmentSelect {
	taq.ctx.Fields = append(taq.ctx.Fields, fields...)
	sbuild := &TaskAttachmentSelect{TaskAttachmentQuery: taq}
	sbuild.label = taskattachment.Label
	sbuild.flds, sbuild.scan = &taq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TaskAttachmentSelect configured with the given aggregations.
func (taq *TaskAttachmentQuery) Aggregate(fns ...AggregateFunc) *TaskAttachmentSelect {
	return taq.Select().Aggregate(fns...)
}

func (taq *TaskAttachmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range taq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, taq); err != nil {
				return err
			}
		}
	}
	for _, f := range taq.ctx.Fields {
		if !taskattachment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *TaskAttachmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaskAttachment, error) {
	var (
		nodes       = []*TaskAttachment{}
		_spec       = taq.querySpec()
		loadedTypes = [1]bool{
			taq.withTask != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaskAttachment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaskAttachment{config: taq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := taq.withTask; query != nil {
		if err := taq.loadTask(ctx, query, nodes, nil,
			func(n *TaskAttachment, e *Task) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (taq *TaskAttachmentQuery) loadTask(ctx context.Context, query *TaskQuery, nodes []*TaskAttachment, init func(*TaskAttachment), assign func(*TaskAttachment, *Task)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TaskAttachment)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (taq *TaskAttachmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	_spec.Node.Columns = taq.ctx.Fields
	if len(taq.ctx.Fields) > 0 {
		_spec.Unique = taq.ctx.Unique != nil && *taq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *TaskAttachmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(taskattachment.Table, taskattachment.Columns, sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeString))
	_spec.From = taq.sql
	if unique := taq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if taq.path != nil {
		_spec.Unique = true
	}
	if fields := taq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskattachment.FieldID)
		for i := range fields {
			if fields[i] != taskattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if taq.withTask != nil {
			_spec.Node.AddColumnOnce(taskattachment.FieldTaskID)
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *TaskAttachmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(taskattachment.Table)
	columns := taq.ctx.Fields
	if len(columns) == 0 {
		columns = taskattachment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if taq.ctx.Unique != nil && *taq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaskAttachmentGroupBy is the group-by builder for TaskAttachment entities.
type TaskAttachmentGroupBy struct {
	selector
	build *TaskAttachmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *TaskAttachmentGroupBy) Aggregate(fns ...AggregateFunc) *TaskAttachmentGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the selector query and scans the result into the given value.
func (tagb *TaskAttachmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tagb.build.ctx, ent.OpQueryGroupBy)
	if err := tagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskAttachmentQuery, *TaskAttachmentGroupBy](ctx, tagb.build, tagb, tagb.build.inters, v)
}

func (tagb *TaskAttachmentGroupBy) sqlScan(ctx context.Context, root *TaskAttachmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tagb.flds)+len(tagb.fns))
		for _, f := range *tagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TaskAttachmentSelect is the builder for selecting fields of TaskAttachment entities.
type TaskAttachmentSelect struct {
	*TaskAttachmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tas *TaskAttachmentSelect) Aggregate(fns ...AggregateFunc) *TaskAttachmentSelect {
	tas.fns = append(tas.fns, fns...)
	return tas
}

// Scan applies the selector query and scans the result into the given value.
func (tas *TaskAttachmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tas.ctx, ent.OpQuerySelect)
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskAttachmentQuery, *TaskAttachmentSelect](ctx, tas.TaskAttachmentQuery, tas, tas.inters, v)
}

func (tas *TaskAttachmentSelect) sqlScan(ctx context.Context, root *TaskAttachmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tas.fns))
	for _, fn := range tas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
