// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/taskchecklistitem"
)

// TaskChecklistItemUpdate is the builder for updating TaskChecklistItem entities.
type TaskChecklistItemUpdate struct {
	config
	hooks    []Hook
	mutation *TaskChecklistItemMutation
}

// Where appends a list predicates to the TaskChecklistItemUpdate builder.
func (tciu *TaskChecklistItemUpdate) Where(ps ...predicate.TaskChecklistItem) *TaskChecklistItemUpdate {
	tciu.mutation.Where(ps...)
	return tciu
}

// SetText sets the "text" field.
func (tciu *TaskChecklistItemUpdate) SetText(s string) *TaskChecklistItemUpdate {
	tciu.mutation.SetText(s)
	return tciu
}

// SetNillableText sets the "text" field if the given value is not nil.
func (tciu *TaskChecklistItemUpdate) SetNillableText(s *string) *TaskChecklistItemUpdate {
	if s != nil {
		tciu.SetText(*s)
	}
	return tciu
}

// SetChecked sets the "checked" field.
func (tciu *TaskChecklistItemUpdate) SetChecked(b bool) *TaskChecklistItemUpdate {
	tciu.mutation.SetChecked(b)
	return tciu
}

// SetNillableChecked sets the "checked" field if the given value is not nil.
func (tciu *TaskChecklistItemUpdate) SetNillableChecked(b *bool) *TaskChecklistItemUpdate {
	if b != nil {
		tciu.SetChecked(*b)
	}
	return tciu
}

// Mutation returns the TaskChecklistItemMutation object of the builder.
func (tciu *TaskChecklistItemUpdate) Mutation() *TaskChecklistItemMutation {
	return tciu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tciu *TaskChecklistItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tciu.sqlSave, tciu.mutation, tciu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tciu *TaskChecklistItemUpdate) SaveX(ctx context.Context) int {
	affected, err := tciu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tciu *TaskChecklistItemUpdate) Exec(ctx context.Context) error {
	_, err := tciu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tciu *TaskChecklistItemUpdate) ExecX(ctx context.Context) {
	if err := tciu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tciu *TaskChecklistItemUpdate) check() error {
	if v, ok := tciu.mutation.Text(); ok {
		if err := taskchecklistitem.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "TaskChecklistItem.text": %w`, err)}
		}
	}
	if tciu.mutation.TaskCleared() && len(tciu.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskChecklistItem.task"`)
	}
	return nil
}

func (tciu *TaskChecklistItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tciu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskchecklistitem.Table, taskchecklistitem.Columns, sqlgraph.NewFieldSpec(taskchecklistitem.FieldID, field.TypeString))
	if ps := tciu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tciu.mutation.Text(); ok {
		_spec.SetField(taskchecklistitem.FieldText, field.TypeString, value)
	}
	if value, ok := tciu.mutation.Checked(); ok {
		_spec.SetField(taskchecklistitem.FieldChecked, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tciu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskchecklistitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tciu.mutation.done = true
	return n, nil
}

// TaskChecklistItemUpdateOne is the builder for updating a single TaskChecklistItem entity.
type TaskChecklistItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskChecklistItemMutation
}

// SetText sets the "text" field.
func (tciuo *TaskChecklistItemUpdateOne) SetText(s string) *TaskChecklistItemUpdateOne {
	tciuo.mutation.SetText(s)
	return tciuo
}

// SetNillableText sets the "text" field if the given value is not nil.
func (tciuo *TaskChecklistItemUpdateOne) SetNillableText(s *string) *TaskChecklistItemUpdateOne {
	if s != nil {
		tciuo.SetText(*s)
	}
	return tciuo
}

// SetChecked sets the "checked" field.
func (tciuo *TaskChecklistItemUpdateOne) SetChecked(b bool) *TaskChecklistItemUpdateOne {
	tciuo.mutation.SetChecked(b)
	return tciuo
}

// SetNillableChecked sets the "checked" field if the given value is not nil.
func (tciuo *TaskChecklistItemUpdateOne) SetNillableChecked(b *bool) *TaskChecklistItemUpdateOne {
	if b != nil {
		tciuo.SetChecked(*b)
	}
	return tciuo
}

// Mutation returns the TaskChecklistItemMutation object of the builder.
func (tciuo *TaskChecklistItemUpdateOne) Mutation() *TaskChecklistItemMutation {
	return tciuo.mutation
}

// Where appends a list predicates to the TaskChecklistItemUpdate builder.
func (tciuo *TaskChecklistItemUpdateOne) Where(ps ...predicate.TaskChecklistItem) *TaskChecklistItemUpdateOne {
	tciuo.mutation.Where(ps...)
	return tciuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tciuo *TaskChecklistItemUpdateOne) Select(field string, fields ...string) *TaskChecklistItemUpdateOne {
	tciuo.fields = append([]string{field}, fields...)
	return tciuo
}

// Save executes the query and returns the updated TaskChecklistItem entity.
func (tciuo *TaskChecklistItemUpdateOne) Save(ctx context.Context) (*TaskChecklistItem, error) {
	return withHooks(ctx, tciuo.sqlSave, tciuo.mutation, tciuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tciuo *TaskChecklistItemUpdateOne) SaveX(ctx context.Context) *TaskChecklistItem {
	node, err := tciuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tciuo *TaskChecklistItemUpdateOne) Exec(ctx context.Context) error {
	_, err := tciuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tciuo *TaskChecklistItemUpdateOne) ExecX(ctx context.Context) {
	if err := tciuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tciuo *TaskChecklistItemUpdateOne) check() error {
	if v, ok := tciuo.mutation.Text(); ok {
		if err := taskchecklistitem.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "TaskChecklistItem.text": %w`, err)}
		}
	}
	if tciuo.mutation.TaskCleared() && len(tciuo.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskChecklistItem.task"`)
	}
	return nil
}

func (tciuo *TaskChecklistItemUpdateOne) sqlSave(ctx context.Context) (_node *TaskChecklistItem, err error) {
	if err := tciuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskchecklistitem.Table, taskchecklistitem.Columns, sqlgraph.NewFieldSpec(taskchecklistitem.FieldID, field.TypeString))
	id, ok := tciuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskChecklistItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tciuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskchecklistitem.FieldID)
		for _, f := range fields {
			if !taskchecklistitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskchecklistitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tciuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tciuo.mutation.Text(); ok {
		_spec.SetField(taskchecklistitem.FieldText, field.TypeString, value)
	}
	if value, ok := tciuo.mutation.Checked(); ok {
		_spec.SetField(taskchecklistitem.FieldChecked, field.TypeBool, value)
	}
	_node = &TaskChecklistItem{config: tciuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tciuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskchecklistitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tciuo.mutation.done = true
	return _node, nil
}
