// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/taskattachment"
)

// TaskAttachmentUpdate is the builder for updating TaskAttachment entities.
type TaskAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *TaskAttachmentMutation
}

// Where appends a list predicates to the TaskAttachmentUpdate builder.
func (tau *TaskAttachmentUpdate) Where(ps ...predicate.TaskAttachment) *TaskAttachmentUpdate {
	tau.mutation.Where(ps...)
	return tau
}

// SetName sets the "name" field.
func (tau *TaskAttachmentUpdate) SetName(s string) *TaskAttachmentUpdate {
	tau.mutation.SetName(s)
	return tau
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tau *TaskAttachmentUpdate) SetNillableName(s *string) *TaskAttachmentUpdate {
	if s != nil {
		tau.SetName(*s)
	}
	return tau
}

// SetSize sets the "size" field.
func (tau *TaskAttachmentUpdate) SetSize(i int64) *TaskAttachmentUpdate {
	tau.mutation.ResetSize()
	tau.mutation.SetSize(i)
	return tau
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (tau *TaskAttachmentUpdate) SetNillableSize(i *int64) *TaskAttachmentUpdate {
	if i != nil {
		tau.SetSize(*i)
	}
	return tau
}

// AddSize adds i to the "size" field.
func (tau *TaskAttachmentUpdate) AddSize(i int64) *TaskAttachmentUpdate {
	tau.mutation.AddSize(i)
	return tau
}

// SetMimeType sets the "mime_type" field.
func (tau *TaskAttachmentUpdate) SetMimeType(s string) *TaskAttachmentUpdate {
	tau.mutation.SetMimeType(s)
	return tau
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (tau *TaskAttachmentUpdate) SetNillableMimeType(s *string) *TaskAttachmentUpdate {
	if s != nil {
		tau.SetMimeType(*s)
	}
	return tau
}

// SetStorageKey sets the "storage_key" field.
func (tau *TaskAttachmentUpdate) SetStorageKey(s string) *TaskAttachmentUpdate {
	tau.mutation.SetStorageKey(s)
	return tau
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (tau *TaskAttachmentUpdate) SetNillableStorageKey(s *string) *TaskAttachmentUpdate {
	if s != nil {
		tau.SetStorageKey(*s)
	}
	return tau
}

// SetURL sets the "url" field.
func (tau *TaskAttachmentUpdate) SetURL(s string) *TaskAttachmentUpdate {
	tau.mutation.SetURL(s)
	return tau
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (tau *TaskAttachmentUpdate) SetNillableURL(s *string) *TaskAttachmentUpdate {
	if s != nil {
		tau.SetURL(*s)
	}
	return tau
}

// Mutation returns the TaskAttachmentMutation object of the builder.
func (tau *TaskAttachmentUpdate) Mutation() *TaskAttachmentMutation {
	return tau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tau *TaskAttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tau.sqlSave, tau.mutation, tau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tau *TaskAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := tau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tau *TaskAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := tau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tau *TaskAttachmentUpdate) ExecX(ctx context.Context) {
	if err := tau.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tau *TaskAttachmentUpdate) check() error {
	if v, ok := tau.mutation.Name(); ok {
		if err := taskattachment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.name": %w`, err)}
		}
	}
	if v, ok := tau.mutation.Size(); ok {
		if err := taskattachment.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.size": %w`, err)}
		}
	}
	if v, ok := tau.mutation.MimeType(); ok {
		if err := taskattachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.mime_type": %w`, err)}
		}
	}
	if v, ok := tau.mutation.StorageKey(); ok {
		if err := taskattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.storage_key": %w`, err)}
		}
	}
	if v, ok := tau.mutation.URL(); ok {
		if err := taskattachment.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.url": %w`, err)}
		}
	}
	if tau.mutation.TaskCleared() && len(tau.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAttachment.task"`)
	}
	return nil
}

func (tau *TaskAttachmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskattachment.Table, taskattachment.Columns, sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeString))
	if ps := tau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tau.mutation.Name(); ok {
		_spec.SetField(taskattachment.FieldName, field.TypeString, value)
	}
	if value, ok := tau.mutation.Size(); ok {
		_spec.SetField(taskattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := tau.mutation.AddedSize(); ok {
		_spec.AddField(taskattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := tau.mutation.MimeType(); ok {
		_spec.SetField(taskattachment.FieldMimeType, field.TypeString, value)
	}
	if value, ok := tau.mutation.StorageKey(); ok {
		_spec.SetField(taskattachment.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := tau.mutation.URL(); ok {
		_spec.SetField(taskattachment.FieldURL, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tau.mutation.done = true
	return n, nil
}

// TaskAttachmentUpdateOne is the builder for updating a single TaskAttachment entity.
type TaskAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskAttachmentMutation
}

// SetName sets the "name" field.
func (tauo *TaskAttachmentUpdateOne) SetName(s string) *TaskAttachmentUpdateOne {
	tauo.mutation.SetName(s)
	return tauo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tauo *TaskAttachmentUpdateOne) SetNillableName(s *string) *TaskAttachmentUpdateOne {
	if s != nil {
		tauo.SetName(*s)
	}
	return tauo
}

// SetSize sets the "size" field.
func (tauo *TaskAttachmentUpdateOne) SetSize(i int64) *TaskAttachmentUpdateOne {
	tauo.mutation.ResetSize()
	tauo.mutation.SetSize(i)
	return tauo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (tauo *TaskAttachmentUpdateOne) SetNillableSize(i *int64) *TaskAttachmentUpdateOne {
	if i != nil {
		tauo.SetSize(*i)
	}
	return tauo
}

// AddSize adds i to the "size" field.
func (tauo *TaskAttachmentUpdateOne) AddSize(i int64) *TaskAttachmentUpdateOne {
	tauo.mutation.AddSize(i)
	return tauo
}

// SetMimeType sets the "mime_type" field.
func (tauo *TaskAttachmentUpdateOne) SetMimeType(s string) *TaskAttachmentUpdateOne {
	tauo.mutation.SetMimeType(s)
	return tauo
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (tauo *TaskAttachmentUpdateOne) SetNillableMimeType(s *string) *TaskAttachmentUpdateOne {
	if s != nil {
		tauo.SetMimeType(*s)
	}
	return tauo
}

// SetStorageKey sets the "storage_key" field.
func (tauo *TaskAttachmentUpdateOne) SetStorageKey(s string) *TaskAttachmentUpdateOne {
	tauo.mutation.SetStorageKey(s)
	return tauo
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (tauo *TaskAttachmentUpdateOne) SetNillableStorageKey(s *string) *TaskAttachmentUpdateOne {
	if s != nil {
		tauo.SetStorageKey(*s)
	}
	return tauo
}

// SetURL sets the "url" field.
func (tauo *TaskAttachmentUpdateOne) SetURL(s string) *TaskAttachmentUpdateOne {
	tauo.mutation.SetURL(s)
	return tauo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (tauo *TaskAttachmentUpdateOne) SetNillableURL(s *string) *TaskAttachmentUpdateOne {
	if s != nil {
		tauo.SetURL(*s)
	}
	return tauo
}

// Mutation returns the TaskAttachmentMutation object of the builder.
func (tauo *TaskAttachmentUpdateOne) Mutation() *TaskAttachmentMutation {
	return tauo.mutation
}

// Where appends a list predicates to the TaskAttachmentUpdate builder.
func (tauo *TaskAttachmentUpdateOne) Where(ps ...predicate.TaskAttachment) *TaskAttachmentUpdateOne {
	tauo.mutation.Where(ps...)
	return tauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tauo *TaskAttachmentUpdateOne) Select(field string, fields ...string) *TaskAttachmentUpdateOne {
	tauo.fields = append([]string{field}, fields...)
	return tauo
}

// Save executes the query and returns the updated TaskAttachment entity.
func (tauo *TaskAttachmentUpdateOne) Save(ctx context.Context) (*TaskAttachment, error) {
	return withHooks(ctx, tauo.sqlSave, tauo.mutation, tauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tauo *TaskAttachmentUpdateOne) SaveX(ctx context.Context) *TaskAttachment {
	node, err := tauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tauo *TaskAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := tauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tauo *TaskAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := tauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tauo *TaskAttachmentUpdateOne) check() error {
	if v, ok := tauo.mutation.Name(); ok {
		if err := taskattachment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.name": %w`, err)}
		}
	}
	if v, ok := tauo.mutation.Size(); ok {
		if err := taskattachment.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.size": %w`, err)}
		}
	}
	if v, ok := tauo.mutation.MimeType(); ok {
		if err := taskattachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.mime_type": %w`, err)}
		}
	}
	if v, ok := tauo.mutation.StorageKey(); ok {
		if err := taskattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.storage_key": %w`, err)}
		}
	}
	if v, ok := tauo.mutation.URL(); ok {
		if err := taskattachment.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "TaskAttachment.url": %w`, err)}
		}
	}
	if tauo.mutation.TaskCleared() && len(tauo.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAttachment.task"`)
	}
	return nil
}

func (tauo *TaskAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *TaskAttachment, err error) {
	if err := tauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskattachment.Table, taskattachment.Columns, sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeString))
	id, ok := tauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskattachment.FieldID)
		for _, f := range fields {
			if !taskattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tauo.mutation.Name(); ok {
		_spec.SetField(taskattachment.FieldName, field.TypeString, value)
	}
	if value, ok := tauo.mutation.Size(); ok {
		_spec.SetField(taskattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := tauo.mutation.AddedSize(); ok {
		_spec.AddField(taskattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := tauo.mutation.MimeType(); ok {
		_spec.SetField(taskattachment.FieldMimeType, field.TypeString, value)
	}
	if value, ok := tauo.mutation.StorageKey(); ok {
		_spec.SetField(taskattachment.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := tauo.mutation.URL(); ok {
		_spec.SetField(taskattachment.FieldURL, field.TypeString, value)
	}
	_node = &TaskAttachment{config: tauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tauo.mutation.done = true
	return _node, nil
}
