// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/tasksubtask"
)

// TaskSubtaskDelete is the builder for deleting a TaskSubtask entity.
type TaskSubtaskDelete struct {
	config
	hooks    []Hook
	mutation *TaskSubtaskMutation
}

// Where appends a list predicates to the TaskSubtaskDelete builder.
func (tsd *TaskSubtaskDelete) Where(ps ...predicate.TaskSubtask) *TaskSubtaskDelete {
	tsd.mutation.Where(ps...)
	return tsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tsd *TaskSubtaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tsd.sqlExec, tsd.mutation, tsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tsd *TaskSubtaskDelete) ExecX(ctx context.Context) int {
	n, err := tsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tsd *TaskSubtaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tasksubtask.Table, sqlgraph.NewFieldSpec(tasksubtask.FieldID, field.TypeString))
	if ps := tsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tsd.mutation.done = true
	return affected, err
}

// TaskSubtaskDeleteOne is the builder for deleting a single TaskSubtask entity.
type TaskSubtaskDeleteOne struct {
	tsd *TaskSubtaskDelete
}

// Where appends a list predicates to the TaskSubtaskDelete builder.
func (tsdo *TaskSubtaskDeleteOne) Where(ps ...predicate.TaskSubtask) *TaskSubtaskDeleteOne {
	tsdo.tsd.mutation.Where(ps...)
	return tsdo
}

// Exec executes the deletion query.
func (tsdo *TaskSubtaskDeleteOne) Exec(ctx context.Context) error {
	n, err := tsdo.tsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tasksubtask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tsdo *TaskSubtaskDeleteOne) ExecX(ctx context.Context) {
	if err := tsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
