// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/radius/radius-backend/ent/task"
	"github.com/radius/radius-backend/ent/tasksubtask"
)

// TaskSubtask is the model entity for the TaskSubtask schema.
type TaskSubtask struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Done holds the value of the "done" field.
	Done bool `json:"done,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskSubtaskQuery when eager-loading is set.
	Edges        TaskSubtaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskSubtaskEdges holds the relations/edges for other nodes in the graph.
type TaskSubtaskEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskSubtaskEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskSubtask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tasksubtask.FieldDone:
			values[i] = new(sql.NullBool)
		case tasksubtask.FieldID, tasksubtask.FieldTaskID, tasksubtask.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskSubtask fields.
func (ts *TaskSubtask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tasksubtask.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ts.ID = value.String
			}
		case tasksubtask.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				ts.TaskID = value.String
			}
		case tasksubtask.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				ts.Title = value.String
			}
		case tasksubtask.FieldDone:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field done", values[i])
			} else if value.Valid {
				ts.Done = value.Bool
			}
		default:
			ts.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskSubtask.
// This includes values selected through modifiers, order, etc.
func (ts *TaskSubtask) Value(name string) (ent.Value, error) {
	return ts.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskSubtask entity.
func (ts *TaskSubtask) QueryTask() *TaskQuery {
	return NewTaskSubtaskClient(ts.config).QueryTask(ts)
}

// Update returns a builder for updating this TaskSubtask.
// Note that you need to call TaskSubtask.Unwrap() before calling this method if this TaskSubtask
// was returned from a transaction, and the transaction was committed or rolled back.
func (ts *TaskSubtask) Update() *TaskSubtaskUpdateOne {
	return NewTaskSubtaskClient(ts.config).UpdateOne(ts)
}

// Unwrap unwraps the TaskSubtask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ts *TaskSubtask) Unwrap() *TaskSubtask {
	_tx, ok := ts.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskSubtask is not a transactional entity")
	}
	ts.config.driver = _tx.drv
	return ts
}

// String implements the fmt.Stringer.
func (ts *TaskSubtask) String() string {
	var builder strings.Builder
	builder.WriteString("TaskSubtask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ts.ID))
	builder.WriteString("task_id=")
	builder.WriteString(ts.TaskID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(ts.Title)
	builder.WriteString(", ")
	builder.WriteString("done=")
	builder.WriteString(fmt.Sprintf("%v", ts.Done))
	builder.WriteByte(')')
	return builder.String()
}

// TaskSubtasks is a parsable slice of TaskSubtask.
type TaskSubtasks []*TaskSubtask
