// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/radius/radius-backend/ent/boardcolumn"
	"github.com/radius/radius-backend/ent/project"
	"github.com/radius/radius-backend/ent/task"
	"github.com/radius/radius-backend/ent/user"
	"github.com/radius/radius-backend/ent/workspace"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status task.Status `json:"status,omitempty"`
	// ColumnID holds the value of the "column_id" field.
	ColumnID *string `json:"column_id,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority task.Priority `json:"priority,omitempty"`
	// DueAt holds the value of the "due_at" field.
	DueAt *time.Time `json:"due_at,omitempty"`
	// LabelIds holds the value of the "label_ids" field.
	LabelIds []string `json:"label_ids,omitempty"`
	// AssigneeID holds the value of the "assignee_id" field.
	AssigneeID *string `json:"assignee_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges        TaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// Column holds the value of the column edge.
	Column *BoardColumn `json:"column,omitempty"`
	// Assignee holds the value of the assignee edge.
	Assignee *User `json:"assignee,omitempty"`
	// Subtasks holds the value of the subtasks edge.
	Subtasks []*TaskSubtask `json:"subtasks,omitempty"`
	// ChecklistItems holds the value of the checklist_items edge.
	ChecklistItems []*TaskChecklistItem `json:"checklist_items,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*TaskAttachment `json:"attachments,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*TaskComment `json:"comments,omitempty"`
	// ActivityLogs holds the value of the activity_logs edge.
	ActivityLogs []*TaskActivityLog `json:"activity_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [9]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// ColumnOrErr returns the Column value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ColumnOrErr() (*BoardColumn, error) {
	if e.Column != nil {
		return e.Column, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: boardcolumn.Label}
	}
	return nil, &NotLoadedError{edge: "column"}
}

// AssigneeOrErr returns the Assignee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) AssigneeOrErr() (*User, error) {
	if e.Assignee != nil {
		return e.Assignee, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assignee"}
}

// SubtasksOrErr returns the Subtasks value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) SubtasksOrErr() ([]*TaskSubtask, error) {
	if e.loadedTypes[4] {
		return e.Subtasks, nil
	}
	return nil, &NotLoadedError{edge: "subtasks"}
}

// ChecklistItemsOrErr returns the ChecklistItems value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) ChecklistItemsOrErr() ([]*TaskChecklistItem, error) {
	if e.loadedTypes[5] {
		return e.ChecklistItems, nil
	}
	return nil, &NotLoadedError{edge: "checklist_items"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) AttachmentsOrErr() ([]*TaskAttachment, error) {
	if e.loadedTypes[6] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) CommentsOrErr() ([]*TaskComment, error) {
	if e.loadedTypes[7] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// ActivityLogsOrErr returns the ActivityLogs value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) ActivityLogsOrErr() ([]*TaskActivityLog, error) {
	if e.loadedTypes[8] {
		return e.ActivityLogs, nil
	}
	return nil, &NotLoadedError{edge: "activity_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldLabelIds:
			values[i] = new([]byte)
		case task.FieldID, task.FieldProjectID, task.FieldWorkspaceID, task.FieldTitle, task.FieldDescription, task.FieldStatus, task.FieldColumnID, task.FieldPriority, task.FieldAssigneeID:
			values[i] = new(sql.NullString)
		case task.FieldDueAt, task.FieldCreatedAt, task.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (t *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				t.ID = value.String
			}
		case task.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				t.ProjectID = value.String
			}
		case task.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				t.WorkspaceID = value.String
			}
		case task.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				t.Title = value.String
			}
		case task.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				t.Description = new(string)
				*t.Description = value.String
			}
		case task.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				t.Status = task.Status(value.String)
			}
		case task.FieldColumnID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field column_id", values[i])
			} else if value.Valid {
				t.ColumnID = new(string)
				*t.ColumnID = value.String
			}
		case task.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				t.Priority = task.Priority(value.String)
			}
		case task.FieldDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_at", values[i])
			} else if value.Valid {
				t.DueAt = new(time.Time)
				*t.DueAt = value.Time
			}
		case task.FieldLabelIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field label_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &t.LabelIds); err != nil {
					return fmt.Errorf("unmarshal field label_ids: %w", err)
				}
			}
		case task.FieldAssigneeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_id", values[i])
			} else if value.Valid {
				t.AssigneeID = new(string)
				*t.AssigneeID = value.String
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case task.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				t.UpdatedAt = value.Time
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (t *Task) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Task entity.
func (t *Task) QueryProject() *ProjectQuery {
	return NewTaskClient(t.config).QueryProject(t)
}

// QueryWorkspace queries the "workspace" edge of the Task entity.
func (t *Task) QueryWorkspace() *WorkspaceQuery {
	return NewTaskClient(t.config).QueryWorkspace(t)
}

// QueryColumn queries the "column" edge of the Task entity.
func (t *Task) QueryColumn() *BoardColumnQuery {
	return NewTaskClient(t.config).QueryColumn(t)
}

// QueryAssignee queries the "assignee" edge of the Task entity.
func (t *Task) QueryAssignee() *UserQuery {
	return NewTaskClient(t.config).QueryAssignee(t)
}

// QuerySubtasks queries the "subtasks" edge of the Task entity.
func (t *Task) QuerySubtasks() *TaskSubtaskQuery {
	return NewTaskClient(t.config).QuerySubtasks(t)
}

// QueryChecklistItems queries the "checklist_items" edge of the Task entity.
func (t *Task) QueryChecklistItems() *TaskChecklistItemQuery {
	return NewTaskClient(t.config).QueryChecklistItems(t)
}

// QueryAttachments queries the "attachments" edge of the Task entity.
func (t *Task) QueryAttachments() *TaskAttachmentQuery {
	return NewTaskClient(t.config).QueryAttachments(t)
}

// QueryComments queries the "comments" edge of the Task entity.
func (t *Task) QueryComments() *TaskCommentQuery {
	return NewTaskClient(t.config).QueryComments(t)
}

// QueryActivityLogs queries the "activity_logs" edge of the Task entity.
func (t *Task) QueryActivityLogs() *TaskActivityLogQuery {
	return NewTaskClient(t.config).QueryActivityLogs(t)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Task) Update() *TaskUpdateOne {
	return NewTaskClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Task) Unwrap() *Task {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("project_id=")
	builder.WriteString(t.ProjectID)
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(t.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(t.Title)
	builder.WriteString(", ")
	if v := t.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", t.Status))
	builder.WriteString(", ")
	if v := t.ColumnID; v != nil {
		builder.WriteString("column_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", t.Priority))
	builder.WriteString(", ")
	if v := t.DueAt; v != nil {
		builder.WriteString("due_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("label_ids=")
	builder.WriteString(fmt.Sprintf("%v", t.LabelIds))
	builder.WriteString(", ")
	if v := t.AssigneeID; v != nil {
		builder.WriteString("assignee_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(t.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
