// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/task"
	"github.com/radius/radius-backend/ent/taskchecklistitem"
)

// TaskChecklistItemCreate is the builder for creating a TaskChecklistItem entity.
type TaskChecklistItemCreate struct {
	config
	mutation *TaskChecklistItemMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (tcic *TaskChecklistItemCreate) SetTaskID(s string) *TaskChecklistItemCreate {
	tcic.mutation.SetTaskID(s)
	return tcic
}

// SetText sets the "text" field.
func (tcic *TaskChecklistItemCreate) SetText(s string) *TaskChecklistItemCreate {
	tcic.mutation.SetText(s)
	return tcic
}

// SetChecked sets the "checked" field.
func (tcic *TaskChecklistItemCreate) SetChecked(b bool) *TaskChecklistItemCreate {
	tcic.mutation.SetChecked(b)
	return tcic
}

// SetNillableChecked sets the "checked" field if the given value is not nil.
func (tcic *TaskChecklistItemCreate) SetNillableChecked(b *bool) *TaskChecklistItemCreate {
	if b != nil {
		tcic.SetChecked(*b)
	}
	return tcic
}

// SetID sets the "id" field.
func (tcic *TaskChecklistItemCreate) SetID(s string) *TaskChecklistItemCreate {
	tcic.mutation.SetID(s)
	return tcic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tcic *TaskChecklistItemCreate) SetNillableID(s *string) *TaskChecklistItemCreate {
	if s != nil {
		tcic.SetID(*s)
	}
	return tcic
}

// SetTask sets the "task" edge to the Task entity.
func (tcic *TaskChecklistItemCreate) SetTask(t *Task) *TaskChecklistItemCreate {
	return tcic.SetTaskID(t.ID)
}

// Mutation returns the TaskChecklistItemMutation object of the builder.
func (tcic *TaskChecklistItemCreate) Mutation() *TaskChecklistItemMutation {
	return tcic.mutation
}

// Save creates the TaskChecklistItem in the database.
func (tcic *TaskChecklistItemCreate) Save(ctx context.Context) (*TaskChecklistItem, error) {
	tcic.defaults()
	return withHooks(ctx, tcic.sqlSave, tcic.mutation, tcic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tcic *TaskChecklistItemCreate) SaveX(ctx context.Context) *TaskChecklistItem {
	v, err := tcic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcic *TaskChecklistItemCreate) Exec(ctx context.Context) error {
	_, err := tcic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcic *TaskChecklistItemCreate) ExecX(ctx context.Context) {
	if err := tcic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tcic *TaskChecklistItemCreate) defaults() {
	if _, ok := tcic.mutation.Checked(); !ok {
		v := taskchecklistitem.DefaultChecked
		tcic.mutation.SetChecked(v)
	}
	if _, ok := tcic.mutation.ID(); !ok {
		v := taskchecklistitem.DefaultID
		tcic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcic *TaskChecklistItemCreate) check() error {
	if _, ok := tcic.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskChecklistItem.task_id"`)}
	}
	if _, ok := tcic.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "TaskChecklistItem.text"`)}
	}
	if v, ok := tcic.mutation.Text(); ok {
		if err := taskchecklistitem.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "TaskChecklistItem.text": %w`, err)}
		}
	}
	if _, ok := tcic.mutation.Checked(); !ok {
		return &ValidationError{Name: "checked", err: errors.New(`ent: missing required field "TaskChecklistItem.checked"`)}
	}
	if len(tcic.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskChecklistItem.task"`)}
	}
	return nil
}

func (tcic *TaskChecklistItemCreate) sqlSave(ctx context.Context) (*TaskChecklistItem, error) {
	if err := tcic.check(); err != nil {
		return nil, err
	}
	_node, _spec := tcic.createSpec()
	if err := sqlgraph.CreateNode(ctx, tcic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TaskChecklistItem.ID type: %T", _spec.ID.Value)
		}
	}
	tcic.mutation.id = &_node.ID
	tcic.mutation.done = true
	return _node, nil
}

func (tcic *TaskChecklistItemCreate) createSpec() (*TaskChecklistItem, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskChecklistItem{config: tcic.config}
		_spec = sqlgraph.NewCreateSpec(taskchecklistitem.Table, sqlgraph.NewFieldSpec(taskchecklistitem.FieldID, field.TypeString))
	)
	if id, ok := tcic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tcic.mutation.Text(); ok {
		_spec.SetField(taskchecklistitem.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := tcic.mutation.Checked(); ok {
		_spec.SetField(taskchecklistitem.FieldChecked, field.TypeBool, value)
		_node.Checked = value
	}
	if nodes := tcic.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskchecklistitem.TaskTable,
			Columns: []string{taskchecklistitem.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskChecklistItemCreateBulk is the builder for creating many TaskChecklistItem entities in bulk.
type TaskChecklistItemCreateBulk struct {
	config
	err      error
	builders []*TaskChecklistItemCreate
}

// Save creates the TaskChecklistItem entities in the database.
func (tcicb *TaskChecklistItemCreateBulk) Save(ctx context.Context) ([]*TaskChecklistItem, error) {
	if tcicb.err != nil {
		return nil, tcicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcicb.builders))
	nodes := make([]*TaskChecklistItem, len(tcicb.builders))
	mutators := make([]Mutator, len(tcicb.builders))
	for i := range tcicb.builders {
		func(i int, root context.Context) {
			builder := tcicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskChecklistItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcicb *TaskChecklistItemCreateBulk) SaveX(ctx context.Context) []*TaskChecklistItem {
	v, err := tcicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcicb *TaskChecklistItemCreateBulk) Exec(ctx context.Context) error {
	_, err := tcicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcicb *TaskChecklistItemCreateBulk) ExecX(ctx context.Context) {
	if err := tcicb.Exec(ctx); err != nil {
		panic(err)
	}
}
