// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/radius/radius-backend/ent/task"
	"github.com/radius/radius-backend/ent/taskactivitylog"
)

// TaskActivityLog is the model entity for the TaskActivityLog schema.
type TaskActivityLog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskActivityLogQuery when eager-loading is set.
	Edges        TaskActivityLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskActivityLogEdges holds the relations/edges for other nodes in the graph.
type TaskActivityLogEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskActivityLogEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskActivityLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskactivitylog.FieldID, taskactivitylog.FieldTaskID, taskactivitylog.FieldTitle, taskactivitylog.FieldDescription, taskactivitylog.FieldIcon:
			values[i] = new(sql.NullString)
		case taskactivitylog.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskActivityLog fields.
func (tal *TaskActivityLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskactivitylog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				tal.ID = value.String
			}
		case taskactivitylog.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				tal.TaskID = value.String
			}
		case taskactivitylog.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				tal.Title = value.String
			}
		case taskactivitylog.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				tal.Description = new(string)
				*tal.Description = value.String
			}
		case taskactivitylog.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				tal.Icon = value.String
			}
		case taskactivitylog.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				tal.OccurredAt = value.Time
			}
		default:
			tal.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskActivityLog.
// This includes values selected through modifiers, order, etc.
func (tal *TaskActivityLog) Value(name string) (ent.Value, error) {
	return tal.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskActivityLog entity.
func (tal *TaskActivityLog) QueryTask() *TaskQuery {
	return NewTaskActivityLogClient(tal.config).QueryTask(tal)
}

// Update returns a builder for updating this TaskActivityLog.
// Note that you need to call TaskActivityLog.Unwrap() before calling this method if this TaskActivityLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (tal *TaskActivityLog) Update() *TaskActivityLogUpdateOne {
	return NewTaskActivityLogClient(tal.config).UpdateOne(tal)
}

// Unwrap unwraps the TaskActivityLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tal *TaskActivityLog) Unwrap() *TaskActivityLog {
	_tx, ok := tal.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskActivityLog is not a transactional entity")
	}
	tal.config.driver = _tx.drv
	return tal
}

// String implements the fmt.Stringer.
func (tal *TaskActivityLog) String() string {
	var builder strings.Builder
	builder.WriteString("TaskActivityLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tal.ID))
	builder.WriteString("task_id=")
	builder.WriteString(tal.TaskID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(tal.Title)
	builder.WriteString(", ")
	if v := tal.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(tal.Icon)
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(tal.OccurredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskActivityLogs is a parsable slice of TaskActivityLog.
type TaskActivityLogs []*TaskActivityLog
