// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/tasksubtask"
)

// TaskSubtaskUpdate is the builder for updating TaskSubtask entities.
type TaskSubtaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskSubtaskMutation
}

// Where appends a list predicates to the TaskSubtaskUpdate builder.
func (tsu *TaskSubtaskUpdate) Where(ps ...predicate.TaskSubtask) *TaskSubtaskUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// SetTitle sets the "title" field.
func (tsu *TaskSubtaskUpdate) SetTitle(s string) *TaskSubtaskUpdate {
	tsu.mutation.SetTitle(s)
	return tsu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tsu *TaskSubtaskUpdate) SetNillableTitle(s *string) *TaskSubtaskUpdate {
	if s != nil {
		tsu.SetTitle(*s)
	}
	return tsu
}

// SetDone sets the "done" field.
func (tsu *TaskSubtaskUpdate) SetDone(b bool) *TaskSubtaskUpdate {
	tsu.mutation.SetDone(b)
	return tsu
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (tsu *TaskSubtaskUpdate) SetNillableDone(b *bool) *TaskSubtaskUpdate {
	if b != nil {
		tsu.SetDone(*b)
	}
	return tsu
}

// Mutation returns the TaskSubtaskMutation object of the builder.
func (tsu *TaskSubtaskUpdate) Mutation() *TaskSubtaskMutation {
	return tsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *TaskSubtaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *TaskSubtaskUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *TaskSubtaskUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *TaskSubtaskUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsu *TaskSubtaskUpdate) check() error {
	if v, ok := tsu.mutation.Title(); ok {
		if err := tasksubtask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TaskSubtask.title": %w`, err)}
		}
	}
	if tsu.mutation.TaskCleared() && len(tsu.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskSubtask.task"`)
	}
	return nil
}

func (tsu *TaskSubtaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasksubtask.Table, tasksubtask.Columns, sqlgraph.NewFieldSpec(tasksubtask.FieldID, field.TypeString))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsu.mutation.Title(); ok {
		_spec.SetField(tasksubtask.FieldTitle, field.TypeString, value)
	}
	if value, ok := tsu.mutation.Done(); ok {
		_spec.SetField(tasksubtask.FieldDone, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasksubtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// TaskSubtaskUpdateOne is the builder for updating a single TaskSubtask entity.
type TaskSubtaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskSubtaskMutation
}

// SetTitle sets the "title" field.
func (tsuo *TaskSubtaskUpdateOne) SetTitle(s string) *TaskSubtaskUpdateOne {
	tsuo.mutation.SetTitle(s)
	return tsuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tsuo *TaskSubtaskUpdateOne) SetNillableTitle(s *string) *TaskSubtaskUpdateOne {
	if s != nil {
		tsuo.SetTitle(*s)
	}
	return tsuo
}

// SetDone sets the "done" field.
func (tsuo *TaskSubtaskUpdateOne) SetDone(b bool) *TaskSubtaskUpdateOne {
	tsuo.mutation.SetDone(b)
	return tsuo
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (tsuo *TaskSubtaskUpdateOne) SetNillableDone(b *bool) *TaskSubtaskUpdateOne {
	if b != nil {
		tsuo.SetDone(*b)
	}
	return tsuo
}

// Mutation returns the TaskSubtaskMutation object of the builder.
func (tsuo *TaskSubtaskUpdateOne) Mutation() *TaskSubtaskMutation {
	return tsuo.mutation
}

// Where appends a list predicates to the TaskSubtaskUpdate builder.
func (tsuo *TaskSubtaskUpdateOne) Where(ps ...predicate.TaskSubtask) *TaskSubtaskUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *TaskSubtaskUpdateOne) Select(field string, fields ...string) *TaskSubtaskUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated TaskSubtask entity.
func (tsuo *TaskSubtaskUpdateOne) Save(ctx context.Context) (*TaskSubtask, error) {
	return withHooks(ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *TaskSubtaskUpdateOne) SaveX(ctx context.Context) *TaskSubtask {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *TaskSubtaskUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *TaskSubtaskUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsuo *TaskSubtaskUpdateOne) check() error {
	if v, ok := tsuo.mutation.Title(); ok {
		if err := tasksubtask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TaskSubtask.title": %w`, err)}
		}
	}
	if tsuo.mutation.TaskCleared() && len(tsuo.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskSubtask.task"`)
	}
	return nil
}

func (tsuo *TaskSubtaskUpdateOne) sqlSave(ctx context.Context) (_node *TaskSubtask, err error) {
	if err := tsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasksubtask.Table, tasksubtask.Columns, sqlgraph.NewFieldSpec(tasksubtask.FieldID, field.TypeString))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskSubtask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasksubtask.FieldID)
		for _, f := range fields {
			if !tasksubtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tasksubtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsuo.mutation.Title(); ok {
		_spec.SetField(tasksubtask.FieldTitle, field.TypeString, value)
	}
	if value, ok := tsuo.mutation.Done(); ok {
		_spec.SetField(tasksubtask.FieldDone, field.TypeBool, value)
	}
	_node = &TaskSubtask{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasksubtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
