// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/taskchecklistitem"
)

// TaskChecklistItemDelete is the builder for deleting a TaskChecklistItem entity.
type TaskChecklistItemDelete struct {
	config
	hooks    []Hook
	mutation *TaskChecklistItemMutation
}

// Where appends a list predicates to the TaskChecklistItemDelete builder.
func (tcid *TaskChecklistItemDelete) Where(ps ...predicate.TaskChecklistItem) *TaskChecklistItemDelete {
	tcid.mutation.Where(ps...)
	return tcid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tcid *TaskChecklistItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tcid.sqlExec, tcid.mutation, tcid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tcid *TaskChecklistItemDelete) ExecX(ctx context.Context) int {
	n, err := tcid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tcid *TaskChecklistItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskchecklistitem.Table, sqlgraph.NewFieldSpec(taskchecklistitem.FieldID, field.TypeString))
	if ps := tcid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tcid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tcid.mutation.done = true
	return affected, err
}

// TaskChecklistItemDeleteOne is the builder for deleting a single TaskChecklistItem entity.
type TaskChecklistItemDeleteOne struct {
	tcid *TaskChecklistItemDelete
}

// Where appends a list predicates to the TaskChecklistItemDelete builder.
func (tcido *TaskChecklistItemDeleteOne) Where(ps ...predicate.TaskChecklistItem) *TaskChecklistItemDeleteOne {
	tcido.tcid.mutation.Where(ps...)
	return tcido
}

// Exec executes the deletion query.
func (tcido *TaskChecklistItemDeleteOne) Exec(ctx context.Context) error {
	n, err := tcido.tcid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskchecklistitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tcido *TaskChecklistItemDeleteOne) ExecX(ctx context.Context) {
	if err := tcido.Exec(ctx); err != nil {
		panic(err)
	}
}
