// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/user"
	"github.com/radius/radius-backend/ent/useroauthaccount"
)

// UserOAuthAccountCreate is the builder for creating a UserOAuthAccount entity.
type UserOAuthAccountCreate struct {
	config
	mutation *UserOAuthAccountMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (uoac *UserOAuthAccountCreate) SetUserID(s string) *UserOAuthAccountCreate {
	uoac.mutation.SetUserID(s)
	return uoac
}

// SetProvider sets the "provider" field.
func (uoac *UserOAuthAccountCreate) SetProvider(s string) *UserOAuthAccountCreate {
	uoac.mutation.SetProvider(s)
	return uoac
}

// SetProviderUserID sets the "provider_user_id" field.
func (uoac *UserOAuthAccountCreate) SetProviderUserID(s string) *UserOAuthAccountCreate {
	uoac.mutation.SetProviderUserID(s)
	return uoac
}

// SetCreatedAt sets the "created_at" field.
func (uoac *UserOAuthAccountCreate) SetCreatedAt(t time.Time) *UserOAuthAccountCreate {
	uoac.mutation.SetCreatedAt(t)
	return uoac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uoac *UserOAuthAccountCreate) SetNillableCreatedAt(t *time.Time) *UserOAuthAccountCreate {
	if t != nil {
		uoac.SetCreatedAt(*t)
	}
	return uoac
}

// SetUpdatedAt sets the "updated_at" field.
func (uoac *UserOAuthAccountCreate) SetUpdatedAt(t time.Time) *UserOAuthAccountCreate {
	uoac.mutation.SetUpdatedAt(t)
	return uoac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uoac *UserOAuthAccountCreate) SetNillableUpdatedAt(t *time.Time) *UserOAuthAccountCreate {
	if t != nil {
		uoac.SetUpdatedAt(*t)
	}
	return uoac
}

// SetID sets the "id" field.
func (uoac *UserOAuthAccountCreate) SetID(s string) *UserOAuthAccountCreate {
	uoac.mutation.SetID(s)
	return uoac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (uoac *UserOAuthAccountCreate) SetNillableID(s *string) *UserOAuthAccountCreate {
	if s != nil {
		uoac.SetID(*s)
	}
	return uoac
}

// SetUser sets the "user" edge to the User entity.
func (uoac *UserOAuthAccountCreate) SetUser(u *User) *UserOAuthAccountCreate {
	return uoac.SetUserID(u.ID)
}

// Mutation returns the UserOAuthAccountMutation object of the builder.
func (uoac *UserOAuthAccountCreate) Mutation() *UserOAuthAccountMutation {
	return uoac.mutation
}

// Save creates the UserOAuthAccount in the database.
func (uoac *UserOAuthAccountCreate) Save(ctx context.Context) (*UserOAuthAccount, error) {
	uoac.defaults()
	return withHooks(ctx, uoac.sqlSave, uoac.mutation, uoac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uoac *UserOAuthAccountCreate) SaveX(ctx context.Context) *UserOAuthAccount {
	v, err := uoac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uoac *UserOAuthAccountCreate) Exec(ctx context.Context) error {
	_, err := uoac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoac *UserOAuthAccountCreate) ExecX(ctx context.Context) {
	if err := uoac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uoac *UserOAuthAccountCreate) defaults() {
	if _, ok := uoac.mutation.CreatedAt(); !ok {
		v := useroauthaccount.DefaultCreatedAt()
		uoac.mutation.SetCreatedAt(v)
	}
	if _, ok := uoac.mutation.UpdatedAt(); !ok {
		v := useroauthaccount.DefaultUpdatedAt()
		uoac.mutation.SetUpdatedAt(v)
	}
	if _, ok := uoac.mutation.ID(); !ok {
		v := useroauthaccount.DefaultID
		uoac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uoac *UserOAuthAccountCreate) check() error {
	if _, ok := uoac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserOAuthAccount.user_id"`)}
	}
	if _, ok := uoac.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UserOAuthAccount.provider"`)}
	}
	if v, ok := uoac.mutation.Provider(); ok {
		if err := useroauthaccount.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserOAuthAccount.provider": %w`, err)}
		}
	}
	if _, ok := uoac.mutation.ProviderUserID(); !ok {
		return &ValidationError{Name: "provider_user_id", err: errors.New(`ent: missing required field "UserOAuthAccount.provider_user_id"`)}
	}
	if v, ok := uoac.mutation.ProviderUserID(); ok {
		if err := useroauthaccount.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserOAuthAccount.provider_user_id": %w`, err)}
		}
	}
	if _, ok := uoac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserOAuthAccount.created_at"`)}
	}
	if _, ok := uoac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserOAuthAccount.updated_at"`)}
	}
	if len(uoac.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserOAuthAccount.user"`)}
	}
	return nil
}

func (uoac *UserOAuthAccountCreate) sqlSave(ctx context.Context) (*UserOAuthAccount, error) {
	if err := uoac.check(); err != nil {
		return nil, err
	}
	_node, _spec := uoac.createSpec()
	if err := sqlgraph.CreateNode(ctx, uoac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserOAuthAccount.ID type: %T", _spec.ID.Value)
		}
	}
	uoac.mutation.id = &_node.ID
	uoac.mutation.done = true
	return _node, nil
}

func (uoac *UserOAuthAccountCreate) createSpec() (*UserOAuthAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &UserOAuthAccount{config: uoac.config}
		_spec = sqlgraph.NewCreateSpec(useroauthaccount.Table, sqlgraph.NewFieldSpec(useroauthaccount.FieldID, field.TypeString))
	)
	if id, ok := uoac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uoac.mutation.Provider(); ok {
		_spec.SetField(useroauthaccount.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := uoac.mutation.ProviderUserID(); ok {
		_spec.SetField(useroauthaccount.FieldProviderUserID, field.TypeString, value)
		_node.ProviderUserID = value
	}
	if value, ok := uoac.mutation.CreatedAt(); ok {
		_spec.SetField(useroauthaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uoac.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauthaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := uoac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useroauthaccount.UserTable,
			Columns: []string{useroauthaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserOAuthAccountCreateBulk is the builder for creating many UserOAuthAccount entities in bulk.
type UserOAuthAccountCreateBulk struct {
	config
	err      error
	builders []*UserOAuthAccountCreate
}

// Save creates the UserOAuthAccount entities in the database.
func (uoacb *UserOAuthAccountCreateBulk) Save(ctx context.Context) ([]*UserOAuthAccount, error) {
	if uoacb.err != nil {
		return nil, uoacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uoacb.builders))
	nodes := make([]*UserOAuthAccount, len(uoacb.builders))
	mutators := make([]Mutator, len(uoacb.builders))
	for i := range uoacb.builders {
		func(i int, root context.Context) {
			builder := uoacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserOAuthAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uoacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uoacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uoacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uoacb *UserOAuthAccountCreateBulk) SaveX(ctx context.Context) []*UserOAuthAccount {
	v, err := uoacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uoacb *UserOAuthAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := uoacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoacb *UserOAuthAccountCreateBulk) ExecX(ctx context.Context) {
	if err := uoacb.Exec(ctx); err != nil {
		panic(err)
	}
}
