// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/useroauthaccount"
)

// UserOAuthAccountUpdate is the builder for updating UserOAuthAccount entities.
type UserOAuthAccountUpdate struct {
	config
	hooks    []Hook
	mutation *UserOAuthAccountMutation
}

// Where appends a list predicates to the UserOAuthAccountUpdate builder.
func (uoau *UserOAuthAccountUpdate) Where(ps ...predicate.UserOAuthAccount) *UserOAuthAccountUpdate {
	uoau.mutation.Where(ps...)
	return uoau
}

// SetProvider sets the "provider" field.
func (uoau *UserOAuthAccountUpdate) SetProvider(s string) *UserOAuthAccountUpdate {
	uoau.mutation.SetProvider(s)
	return uoau
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (uoau *UserOAuthAccountUpdate) SetNillableProvider(s *string) *UserOAuthAccountUpdate {
	if s != nil {
		uoau.SetProvider(*s)
	}
	return uoau
}

// SetProviderUserID sets the "provider_user_id" field.
func (uoau *UserOAuthAccountUpdate) SetProviderUserID(s string) *UserOAuthAccountUpdate {
	uoau.mutation.SetProviderUserID(s)
	return uoau
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (uoau *UserOAuthAccountUpdate) SetNillableProviderUserID(s *string) *UserOAuthAccountUpdate {
	if s != nil {
		uoau.SetProviderUserID(*s)
	}
	return uoau
}

// SetUpdatedAt sets the "updated_at" field.
func (uoau *UserOAuthAccountUpdate) SetUpdatedAt(t time.Time) *UserOAuthAccountUpdate {
	uoau.mutation.SetUpdatedAt(t)
	return uoau
}

// Mutation returns the UserOAuthAccountMutation object of the builder.
func (uoau *UserOAuthAccountUpdate) Mutation() *UserOAuthAccountMutation {
	return uoau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uoau *UserOAuthAccountUpdate) Save(ctx context.Context) (int, error) {
	uoau.defaults()
	return withHooks(ctx, uoau.sqlSave, uoau.mutation, uoau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uoau *UserOAuthAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := uoau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uoau *UserOAuthAccountUpdate) Exec(ctx context.Context) error {
	_, err := uoau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoau *UserOAuthAccountUpdate) ExecX(ctx context.Context) {
	if err := uoau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uoau *UserOAuthAccountUpdate) defaults() {
	if _, ok := uoau.mutation.UpdatedAt(); !ok {
		v := useroauthaccount.UpdateDefaultUpdatedAt()
		uoau.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uoau *UserOAuthAccountUpdate) check() error {
	if v, ok := uoau.mutation.Provider(); ok {
		if err := useroauthaccount.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserOAuthAccount.provider": %w`, err)}
		}
	}
	if v, ok := uoau.mutation.ProviderUserID(); ok {
		if err := useroauthaccount.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserOAuthAccount.provider_user_id": %w`, err)}
		}
	}
	if uoau.mutation.UserCleared() && len(uoau.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOAuthAccount.user"`)
	}
	return nil
}

func (uoau *UserOAuthAccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uoau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(useroauthaccount.Table, useroauthaccount.Columns, sqlgraph.NewFieldSpec(useroauthaccount.FieldID, field.TypeString))
	if ps := uoau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uoau.mutation.Provider(); ok {
		_spec.SetField(useroauthaccount.FieldProvider, field.TypeString, value)
	}
	if value, ok := uoau.mutation.ProviderUserID(); ok {
		_spec.SetField(useroauthaccount.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := uoau.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauthaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uoau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroauthaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uoau.mutation.done = true
	return n, nil
}

// UserOAuthAccountUpdateOne is the builder for updating a single UserOAuthAccount entity.
type UserOAuthAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserOAuthAccountMutation
}

// SetProvider sets the "provider" field.
func (uoauo *UserOAuthAccountUpdateOne) SetProvider(s string) *UserOAuthAccountUpdateOne {
	uoauo.mutation.SetProvider(s)
	return uoauo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (uoauo *UserOAuthAccountUpdateOne) SetNillableProvider(s *string) *UserOAuthAccountUpdateOne {
	if s != nil {
		uoauo.SetProvider(*s)
	}
	return uoauo
}

// SetProviderUserID sets the "provider_user_id" field.
func (uoauo *UserOAuthAccountUpdateOne) SetProviderUserID(s string) *UserOAuthAccountUpdateOne {
	uoauo.mutation.SetProviderUserID(s)
	return uoauo
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (uoauo *UserOAuthAccountUpdateOne) SetNillableProviderUserID(s *string) *UserOAuthAccountUpdateOne {
	if s != nil {
		uoauo.SetProviderUserID(*s)
	}
	return uoauo
}

// SetUpdatedAt sets the "updated_at" field.
func (uoauo *UserOAuthAccountUpdateOne) SetUpdatedAt(t time.Time) *UserOAuthAccountUpdateOne {
	uoauo.mutation.SetUpdatedAt(t)
	return uoauo
}

// Mutation returns the UserOAuthAccountMutation object of the builder.
func (uoauo *UserOAuthAccountUpdateOne) Mutation() *UserOAuthAccountMutation {
	return uoauo.mutation
}

// Where appends a list predicates to the UserOAuthAccountUpdate builder.
func (uoauo *UserOAuthAccountUpdateOne) Where(ps ...predicate.UserOAuthAccount) *UserOAuthAccountUpdateOne {
	uoauo.mutation.Where(ps...)
	return uoauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uoauo *UserOAuthAccountUpdateOne) Select(field string, fields ...string) *UserOAuthAccountUpdateOne {
	uoauo.fields = append([]string{field}, fields...)
	return uoauo
}

// Save executes the query and returns the updated UserOAuthAccount entity.
func (uoauo *UserOAuthAccountUpdateOne) Save(ctx context.Context) (*UserOAuthAccount, error) {
	uoauo.defaults()
	return withHooks(ctx, uoauo.sqlSave, uoauo.mutation, uoauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uoauo *UserOAuthAccountUpdateOne) SaveX(ctx context.Context) *UserOAuthAccount {
	node, err := uoauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uoauo *UserOAuthAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := uoauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uoauo *UserOAuthAccountUpdateOne) ExecX(ctx context.Context) {
	if err := uoauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uoauo *UserOAuthAccountUpdateOne) defaults() {
	if _, ok := uoauo.mutation.UpdatedAt(); !ok {
		v := useroauthaccount.UpdateDefaultUpdatedAt()
		uoauo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uoauo *UserOAuthAccountUpdateOne) check() error {
	if v, ok := uoauo.mutation.Provider(); ok {
		if err := useroauthaccount.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserOAuthAccount.provider": %w`, err)}
		}
	}
	if v, ok := uoauo.mutation.ProviderUserID(); ok {
		if err := useroauthaccount.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserOAuthAccount.provider_user_id": %w`, err)}
		}
	}
	if uoauo.mutation.UserCleared() && len(uoauo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOAuthAccount.user"`)
	}
	return nil
}

func (uoauo *UserOAuthAccountUpdateOne) sqlSave(ctx context.Context) (_node *UserOAuthAccount, err error) {
	if err := uoauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useroauthaccount.Table, useroauthaccount.Columns, sqlgraph.NewFieldSpec(useroauthaccount.FieldID, field.TypeString))
	id, ok := uoauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserOAuthAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uoauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroauthaccount.FieldID)
		for _, f := range fields {
			if !useroauthaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useroauthaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uoauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uoauo.mutation.Provider(); ok {
		_spec.SetField(useroauthaccount.FieldProvider, field.TypeString, value)
	}
	if value, ok := uoauo.mutation.ProviderUserID(); ok {
		_spec.SetField(useroauthaccount.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := uoauo.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauthaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserOAuthAccount{config: uoauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uoauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroauthaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uoauo.mutation.done = true
	return _node, nil
}
