// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/radius/radius-backend/ent/predicate"
	"github.com/radius/radius-backend/ent/useroauthaccount"
)

// UserOAuthAccountDelete is the builder for deleting a UserOAuthAccount entity.
type UserOAuthAccountDelete struct {
	config
	hooks    []Hook
	mutation *UserOAuthAccountMutation
}

// Where appends a list predicates to the UserOAuthAccountDelete builder.
func (uoad *UserOAuthAccountDelete) Where(ps ...predicate.UserOAuthAccount) *UserOAuthAccountDelete {
	uoad.mutation.Where(ps...)
	return uoad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uoad *UserOAuthAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uoad.sqlExec, uoad.mutation, uoad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uoad *UserOAuthAccountDelete) ExecX(ctx context.Context) int {
	n, err := uoad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uoad *UserOAuthAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(useroauthaccount.Table, sqlgraph.NewFieldSpec(useroauthaccount.FieldID, field.TypeString))
	if ps := uoad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uoad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uoad.mutation.done = true
	return affected, err
}

// UserOAuthAccountDeleteOne is the builder for deleting a single UserOAuthAccount entity.
type UserOAuthAccountDeleteOne struct {
	uoad *UserOAuthAccountDelete
}

// Where appends a list predicates to the UserOAuthAccountDelete builder.
func (uoado *UserOAuthAccountDeleteOne) Where(ps ...predicate.UserOAuthAccount) *UserOAuthAccountDeleteOne {
	uoado.uoad.mutation.Where(ps...)
	return uoado
}

// Exec executes the deletion query.
func (uoado *UserOAuthAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := uoado.uoad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useroauthaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uoado *UserOAuthAccountDeleteOne) ExecX(ctx context.Context) {
	if err := uoado.Exec(ctx); err != nil {
		panic(err)
	}
}
